### PR TITLE
docs: update mobile phones page by adding security update details

### PR DESCRIPTION
**Pull request by rollsicecream**
Changes proposed in this PR:

- docs: update mobile phones page by adding security update details

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Comment by rollsicecream** [comment]
If anyone can find a better commit description, then reach me out.

**Comment by kimg45** [comment]
Many android phones actually do let you install alternative OS's so you can have more recent versions of Android, so I don't think it's actually accurate to say there's no software updates. The main thing that you can't get without OEM support is firmware updates.

**Comment by rollsicecream** [comment]
Thank you for your feedback @kimg45 ! You make a good point about that. I've revised the PR to clarify this distinction while emphasizing the lack of official firmware updates from the OEM. Here's the updated text, let me know what you think before I push the changes: 

"Most **mobile phones** receive short or limited windows of security updates from OEMs; after these devices reach the end of their support period, they **cannot** be considered secure as they no longer receive firmware, software, or driver security updates from the OEM. While some devices may allow the installation of alternative OSes to obtain more recent software updates, they will still lack official firmware updates from the manufacturer."

**Review by redoomed1 — CHANGES_REQUESTED** [review]
Thanks for the PR!

In reply to the latest [revision](https://github.com/privacyguides/privacyguides.org/pull/2699#issuecomment-2271749276) you offered, I'm not sure this needs to be added in the introduction, as it's already mentioned in the admonition below:

> **Warning**
> End-of-life devices (such as GrapheneOS's "extended support" devices) do not have full security patches (firmware updates) due to the OEM discontinuing support. _These devices cannot be considered completely secure regardless of installed software._

**Comment by rollsicecream** [comment]
So, it's all good I guedd, should I close the PR?

**Comment by redoomed1** [comment]
> should I close the PR?

Yes, the wording is fine on the page as is. Thanks again!

**Pull request closed without merging**
