### PR TITLE
Add Age File Encryption

### LINKED ISSUE #291: Recommend Age
## Description

**URL of affected page:** https://privacyguides.org/software/productivity/#encrypt

https://github.com/FiloSottile/age

### PR DESCRIPTION
**Pull request by dngray**
## Description

Resolves: https://github.com/privacyguides/privacyguides.org/issues/291

This one is waiting on a reply in https://github.com/FiloSottile/age/discussions/217#discussioncomment-1624548

### CODE REVIEW

**Comment by Mikaela** [comment]
> This one is waiting on a reply in FiloSottile/age#217 (comment)

I take it this is not ready for review

**Comment by 1hiking** [comment]
Isn't the logo of Age the one on the [Releases page](https://github.com/FiloSottile/age/releases/tag/v1.0.0)?

**Comment by dngray** [comment]
> Isn't the logo of Age the one on the [Releases page](https://github.com/FiloSottile/age/releases/tag/v1.0.0)?

It is, but I thought they might have had some square versions, or inverted versions. I made some up but don't want to use them unless approved. https://github.com/FiloSottile/age/discussions/217#discussioncomment-1632910

**Review by jonaharagon — APPROVED** [review]
LGTM

**Comment by dngray** [comment]
- Couple of things, logo [svg needs scouring](https://github.com/privacyguides/privacyguides.org/wiki/Contributing#svg)
- I've put a comment here https://github.com/FiloSottile/age/discussions/217#discussioncomment-1892873 hoping we can get permission to use  a "dome only" version which would look a lot better
- I want to provide a bit of an expanded guide, because Age doesn't do signing, we really ought to give some usage examples with signify or minisign.
- We might put a hold on this one and do a legacy page migration.
- We should also consider https://github.com/privacyguides/privacyguides.org/discussions/170 it might be better to mention things with a graphical user interface, rather than commandline tools. Though for tools which "use age" we could mention it in their description.
- We should also take into account a future criteria for this section https://github.com/privacyguides/privacyguides.org/discussions/24#discussioncomment-1744298

**Comment by samuel-lucas6** [comment]
> As we're going away from "Worth mentioning" sections we might elevate Kryptor to a card and mention age in the description.

Thank you if Kryptor does move up to a card. I think I'd put age in a separate card though considering its popularity.

> If this is added I want to provide a bit of an expanded guide, because Age doesn't do signing, we really ought to give some usage examples with signify or minisign.

[InfoSec Handbook](https://infosec-handbook.eu/) has a guide on [Minisign](https://infosec-handbook.eu/tutorials/tool-minisign/) and [signify](https://infosec-handbook.eu/tutorials/tool-signify/), so perhaps those could be linked or used for inspiration.

**Comment by dngray** [comment]
> Thank you if Kryptor does move up to a card. I think I'd put age in a separate card though considering its popularity.

We could certainly do that. I'm thinking we might split it into 3 sections:

We would write about the purposes for each.

- Volume and container
   - Veracrypt
   - Zulucrypt
   - Bitlocker
   - Filevault

- File based encryption
  - Cryptomator
  - Kryptor 
  - Picocrypt etc

- Command line tools
  - Age (minisign/signify)
  - GnuPG
  - cryptsetup
  - Pass

- Web based tools
  - hat.sh

> [InfoSec Handbook](https://infosec-handbook.eu/) has a guide on [Minisign](https://infosec-handbook.eu/tutorials/tool-minisign/) and [signify](https://infosec-handbook.eu/tutorials/tool-signify/), so perhaps those could be linked or used for inspiration.

Those look perfect.

**Comment by samuel-lucas6** [comment]
> We could certainly do that. I'm thinking we might split it into 3 sections:

Yeah, it's a good idea to separate them. Kryptor should probably go in the same section as age and GPG though as it no longer has a GUI (it may come back eventually) and supports file signing. I'd either go with:

- Disk encryption
- GUI file encryption (and signing if there are any GUI signing tools)
- CLI file encryption and signing

Or:

- Disk encryption
- File encryption
- File signing

Hat.sh could go in GUI, pass can go on a different page, cryptsetup could go in Disk encryption, etc. 

I think I prefer the second approach, but I agree that it should be clear which programs have a GUI. It could be ranked on perceived ease of use (e.g. Cryptomator at the top). 

Also, as I said in #24, some algorithm recommendations for programs like VeraCrypt would be wise, such as 'use AES and SHA512' to avoid algorithms like Kuznyechik and Streebog being selected.

**Review by freddy-m — COMMENTED** [review]
Just waiting for the logo now, lol

**Review by freddy-m — APPROVED** [review]

**Comment by dngray** [comment]
I'm not quite so sure we should do this now.

> [InfoSec Handbook](https://infosec-handbook.eu/) has a guide on [Minisign](https://infosec-handbook.eu/tutorials/tool-minisign/) and [signify](https://infosec-handbook.eu/tutorials/tool-signify/), so perhaps those could be linked or used for inspiration.

These guides now seem offline but are available [Minisign](https://web.archive.org/web/20210813101914/https://infosec-handbook.eu/tutorials/tool-minisign/), and [Signify](https://web.archive.org/web/20210814181026/https://infosec-handbook.eu/tutorials/tool-signify/).

We could perhaps write something like this and publish it under a "Security Advanced" section of the site.

As we carefully populate "Security Basics", with digestible content for new people.

**Pull request closed without merging**
