### PR TITLE
add Perfect Forward Secrecy to the abbreviations list

### PR DESCRIPTION
**Pull request by paulverbeke**
- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

### CODE REVIEW

**Comment by dngray** [comment]
I'm thinking we should change this string to "forward secrecy" as the "perfect" doesn't add anything. That is what Wikipedia says too https://en.wikipedia.org/wiki/Forward_secrecy

**Comment by jonaharagon** [comment]
Thanks! I don't think we need to add this though: In #2079 references to "Perfect Forward Secrecy" and "PFS" are going to be replaced with just "forward secrecy", which is the more modern term.

**Comment by paulverbeke** [comment]
great, and what about adding KYC to the abbreviation list ?

**Comment by dngray** [comment]
> KYC to the abbreviation list ?

Yes, that does make sense.

**Pull request closed without merging**
