### PR TITLE
Remove Posteo

### PR DESCRIPTION
**Pull request by tommytran732**
Posteo.de has an arguably quite serious vulnerbility with how they set up their service. I will be discussing this privately with the team and file a report to them later. 

For now though, I do not think they should be recommended anymore.

### CODE REVIEW

**Comment by dngray** [comment]
I'd suggest reaching out to them rather than submitting a PR here.

**Review by dngray — CHANGES_REQUESTED** [review]
I'd suggest reaching out to them before making a PR here.

**Comment by freddy-m** [comment]
Closing this until you have disclosed it with Posteo and have had further information.

**Comment by tommytran732** [comment]
> Closing this until you have disclosed it with Posteo and have had further information.

I contacted them and got a reply. It won't be fixed. I think we should merge this now. We can discuss more in DMs if you want.

**Pull request closed without merging**
