### PR TITLE
Revert pride month logos

### PR DESCRIPTION
**Pull request by dngray**
Changes proposed in this PR:

- 

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Review by freddy-m — APPROVED** [review]

**Review by jonaharagon — CHANGES_REQUESTED** [review]
There are also changes in config/layout that have to be reverted. I’d have to look at the original commit to see everything that was changed, but I can check it out when I get home.

**Comment by dngray** [comment]
That's okay, I checked this with a local preview build and it did seem to look alright, but I wasn't sure.

**Review by jonaharagon — APPROVED** [review]
> I thought there were some permanent changes in https://github.com/privacyguides/privacyguides.org/commit/ff60d624fc79280b9aa0121cb7ff63fadc78da1d which is why I didn't revert it in full.

There were, but there were also some changes to the social preview cards that needed to be reverted. Fixed!

**Comment by jonaharagon** [comment]
We didn't forget, you deleted the change when you merged this.

BECsU6LhYyGnLSfh

**Comment by jonaharagon** [comment]
Also yeah, but I did this one pretty janky this year because mkdocs-material was missing a bunch of features that would've made this easier, which I requested and have been added in the latest version, so next time around we can do this cleanly.

**Pull request merged**
