### PR TITLE
Restructure how to get apps and align the usage of headers.

### PR DESCRIPTION
**Pull request by ph00lt0**
I open this PR because I noticed that the headers used on this Android page are not aligned. Certain apps have Notes with H3 and others H4 so I fixed this now.

While doing this I noticed that the main point of the "Where to get your apps should actually be above all the clients. It makes much more sense to start on where to get apps from and then list the locations rather then in reverse. By making the clients part of this 'section' it feels more like a guide rather then lose statements.

### CODE REVIEW

**Comment by akumeilol** [comment]
I made this same change in #645

**Comment by ph00lt0** [comment]
> I made this same change in #645

I see now @akumeilol I missed that, but just looking at your PR you have some rebasing to do, it currently resets quite some changes.

**Comment by dngray** [comment]
I think this is fixed now https://github.com/privacyguides/privacyguides.org/commit/00f18af4659cd6dd628ae3fdedf95b532b7a5e64

**Comment by ph00lt0** [comment]
@dngray the order of the page is still strange. Where to get apps should be the main header, instead of fdroid above it. 

The proposed structure would be:
Where to get your apps?
- GrapheneOS
- F-Droid
   - Droid-ify
 - Aurora (add new card)

**Comment by dngray** [comment]
@ph00lt0 check out https://github.com/privacyguides/privacyguides.org/pull/955 is that better?

**Pull request closed without merging**
