### PR TITLE
feat: Link to our SimpleX channel

### PR DESCRIPTION
**Pull request by jonaharagon**
List of changes proposed in this PR:

- Link to our read-only [SimpleX channel](https://simplex.chat/contact#/?v=2-7&smp=smp%3A%2F%2F6iIcWT_dF2zN_w5xzZEY7HI2Prbh3ldP07YTyDexPjE%3D%40smp10.simplex.im%2F_9QtlcDXfiJUuyCTl4hjQR-kQK81eP9f%23%2F%3Fv%3D1-3%26dh%3DMCowBQYDK2VuAyEA2l295HnzRCCJvu2uXmhNqkd_uAxvySWOgl2nP9JawGc%253D%26srv%3Drb2pbttocvnbrngnwziclp2f4ckjq65kebafws6g4hy22cdaiv5dwjqd.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%22QyPYAd1Vm4x6Alv34Bef4Q%3D%3D%22%7D)

### CODE REVIEW

**Comment by kimg45** [comment]
This wasn't agreed on.

**Comment by kimg45** [comment]
> Would it be worth opening a forum discussion about this?

idk I just think stuff like #2572 needs to be sorted out before we add more stuff. Just wanna make sure the services already offered are being maintained first before adding more stuff so it doesn't get abandoned.

**Review by blacklight447 — APPROVED** [review]

**Review by friadev — DISMISSED** [review]
Fix other things before adding more

**Review by freddy-m — COMMENTED** [review]
> Fix other things before adding more

I don't think this should be a sitewide policy - but I do thnk we need to give proper consideration to adding a new feature (or whatever) to the site. 

In regards to SimpleX, I'm a big fan of their service but I'm not entirely sure we need to have our own channel given we already have a Matrix space etc. As @kimg45 alludes too, its also another thing that is likely to go unmaintained...

**Comment by friadev** [comment]
Tried to join the link but it got stuck on connecting.

**Pull request closed without merging**
