### PR TITLE
Rainbow Capitalism

### PR DESCRIPTION
**Pull request by jonaharagon**
For one month only, \<sarcasm>then we can go back to hating the gays\</sarcasm>

### CODE REVIEW

**Review by dngray — APPROVED** [review]

**Review by blacklight447 — APPROVED** [review]
Yes.

**Review by hook9 — APPROVED** [review]

**Review by 27lx — COMMENTED** [review]
SVGs looks like they need some optimization 😛

**Comment by RoseTheFlower** [comment]
Quite hypocritical in light of the promotion of Brave.

**Comment by dngray** [comment]
> Quite hypocritical in light of the promotion of Brave.

It's recommended based on technical merit.

It might surprise, but the team is quite diverse. I know of at least one bi, gay and trans member.

**Pull request merged**
