### PR TITLE
Add anchors to the appropriate headings previously missing them

### PR DESCRIPTION
**Pull request by akumeilol**
This PR adds anchors to the appropriate headings that were previously missing it.

Preview: https://deploy-preview-645--privacyguides.netlify.app

## Notes

- I tried to work around the existing codebase as much as possible—I didn't want to break anything by modifying anything too heavily. I've never worked on a Jekyll project this large before.
- **Duplicate heading names (i.e. Advantages, Disadvantages, Notes, etc) should use a tier 4 heading or higher.** Also use tier 4 or higher for unimportant headings.
- Sorry Jonah for likely using up a ton of Netlify build minutes! I could not for the life of me get it to build locally.

## Evergreen markdown anchors

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-9256c9e8ba38aa09096cc4be5bf614026b87485910661016c66e2cfe6fb35d80

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-f706bb2d5260d4b6b065c9d8065984f748f4e35c773e7f7d89d1bc0efd8bb930

Markdown pages using the Evergreen page layout (cool layout name, btw) make use of the [Jekyll Pure Liquid Heading Anchors](https://github.com/allejo/jekyll-anchor-headings) _includes file. This liquid snippet will automatically add anchors to heading levels 2-3, as per my specification. The anchors make use of the same Font Awesome icon that the legacy page anchors use.

I chose to limit the anchors between heading levels 2-3 because it fits nicely with all the pre-existing content. (i.e. headings with the same name typically all use tier 4 headings)

This _includes file can be used in any other page layout in the future.

## cardv2 anchors

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-c91b811f40687e522be3303326295aafcbe9faf555e007976b14799bcdb1e0a5

The titles on the cardv2 _includes will now be anchored. An example of this would be the title of Thunderbird in the desktop email clients section.

This works by taking the title of the card, [slug-ifying](https://jekyllrb.com/docs/liquid/filters/#slugify) it, and using the slug-ified title as a link.

## Recommendation card anchors

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-9bbe2d33f724cdb806827cc4ee7790c3ceae2c81b52cf6cc9cbdb0dac3aa7509

These use the same slug-ify method as cardv2 anchors.

## Specific edits

Not all appropriate headings were anchored using the above additions. So, I went through each page and properly added them.

### Android page

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-9040923903734729b9be0c90740982cb7fe8d244419c8a6af105e740e7e5ff90

One important section in the Android page was using a tier 4 heading and so it did not get picked up by the _includes anchor script thing. This edit increases that heading to a tier 3, which it should've been anyway.

Two recent additions to the Android page also featured inconsistent headings (tier 3) for "Notes." These are changed to tier 4 so they don't get unnecessarily picked up by the anchor generator.

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-6313943d4e2e243ff3bda58cbc07ead96b2cecd96ef20a4a50de78ff211f9b5b

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-18bdf09879fb1fc8dfe54ac7388ba550921ae33222dc6f14a6a8f5c285e8bf59

### Real time communication page

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-f25ee2132251bbf1ef7a355cce8085d3e7d9243debfd10f99146fcc079a04da8

The advantages and disadvantages sections were using inconsistent heading tiers for the different network types. One was using a tier 4, the other two were using a tier 3. Because the headings share the same name (Advantages, Disadvantages), they can't be anchored and therefore should be using a tier 4 heading or higher. This edit makes the headings tier 4 to prevent this, and plus I believe having them as a tier 3 was a mistake in the first place.

### DNS resolver page

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-b36fe86eacf5d6052928d6105b1bc1c01649c964d78b9d4c88605ce0dfffb143

This page didn't get touched at all by the above methods as it uses the page layout. So in this case I switched the markdown headings to html headings.

### VPN page

https://github.com/privacyguides/privacyguides.org/pull/645/files#diff-22fa64dc2bd358e71646a99e2b79eca48f91ac50259af7bd0944922a16193158

This page already had most things anchored manually, however it was missing two at the very bottom of the page.

### CODE REVIEW

**Comment by tommytran732** [comment]
Looking great but I think you should remove the anchor links in the recommendation cards. They look weird there.

**Comment by akumeilol** [comment]
> Looking great but I think you should remove the anchor links in the recommendation cards. They look weird there.

I agree. I think it would still be useful to be able to link to them though, so I'll experiment with a less obtrusive anchor design for those.

**Comment by dngray** [comment]
I rebased this one on main.

**Comment by akumeilol** [comment]
> Looking great but I think you should remove the anchor links in the recommendation cards. They look weird there.

> I agree. I think it would still be useful to be able to link to them though, so I'll experiment with a less obtrusive anchor design for those.

I started looking into this PR again and I don't think it would be possible for me to change the design of them since they're all based off the same foundation, it's either they are there or they aren't.

Despite them maybe looking a bit weird, I think it's important to have the anchors in the recommendation cards. Take the Android page for example. The AOSP cards are massive and require a decent amount of scrolling, so linking directly to them is quite useful.

That aside, I would consider this PR complete.

**Comment by akumeilol** [comment]
oh no i think i just messed up the pr by trying to merge main

**Comment by akumeilol** [comment]
i messed it up even more trying to rebase lol. I'll just take the changes and put them on a fresh branch.

**Comment by dngray** [comment]
I haven't been paying too much attention here, but I wouldn't worry about legacy_pages, we're going to be refactoring most of that anyway into new content/format

**Pull request closed without merging**
