### PR TITLE
Add tvOS encrypted DNS instructions

### PR DESCRIPTION
**Pull request by lx-is**
#828

Since tvOS is mentioned, it's probably best to have instructions for it (especially since it's so unintuitive).

I also edited the macOS instructions to include the secondary location.

### CODE REVIEW

**Comment by lx-is** [comment]
wth happened to this pr

**Comment by dngray** [comment]
it says you closed it.

**Comment by dngray** [comment]
I'll incorporate these changes in https://github.com/privacyguides/privacyguides.org/pull/827

**Comment by lx-is** [comment]
> it says you closed it, and i can't seem to find the branches.

Yeah, I'm not sure how but my entire fork got completely messed up. I had to create a new one.

> I'll incorporate these changes in #827

👍 Cool, thanks.

**Pull request closed without merging**
