### PR TITLE
Revise the first minimum requirement for Search Engines

### LINKED ISSUE #2573: Slight rewording of a minimum requirement for Search Engines
### Affected page

https://www.privacyguides.org/en/search-engines/#minimum-requirements

### Description

Someone on the PG Matrix pointed this out:

> do not have a github, but might want to change search engine minimum requirements for consideration.

    Must not allow users to create an account with them.

> change allow to require, as brave search allows users to pay with an account for premium search

### Sources

https://search.brave.com/help/premium

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

### PR DESCRIPTION
**Pull request by redoomed1**
Changes proposed in this PR:

- Reword the first minimum requirement on the Search Engines page (closes #2573)
  - The current wording of "allow" would disqualify Brave Search, <del>which doesn't seem to be the intention of this minimum requirement. Based on what was expressed in the forum [thread on Kagi](https://discuss.privacyguides.net/t/kagi-search-engine/14172/2), the wording of "require" seems to be more accurate (please correct me if I'm wrong).</del> See https://github.com/privacyguides/privacyguides.org/pull/2579#pullrequestreview-2075633584
- Linux Overview
  - Change links for Whonix and Tails to internal links
  - Correct instructions for disabling openSUSE counting
    - The current guidance on the site recommends deleting the file, but the [linked documentation](https://en.opensuse.org/openSUSE:Statistics) reads
      > In order to not have an installation counted for the statistics the file can be emptied. (Note that deleting the file will not help since the next invocation of zypper dup etc will recreate it with a new UUID.)
- Correct the "custodial wallet" internal link on the Desktop Browser page (current page points to the "Other Coins" section of the Private Payments page)
- Make minor grammar changes on the Search Engines page and the Linux Overview page

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Review by jonaharagon — CHANGES_REQUESTED** [review]
Thanks for the PR!

> which doesn't seem to be the intention of this minimum requirement.

This _was_ actually the intention of the minimum requirement when it was introduced. We just didn't look at Brave Search again when they announced the subscriptions.

I'm okay with changing it, if we note that using Brave Search Premium with an account may make it easier for Brave to correlate queries with specific users.

I would note this (without an admonition) after line 47 and take inspiration from our notes on Mullvad Leta at https://www.privacyguides.org/en/desktop-browsers/#mullvad-leta (although we don't need to be quite as verbose, a sentence or two is fine).

I can also add a suggestion with exact text sometime later if you don't beat me to it.

**Comment by redoomed1** [comment]
> I'm okay with changing it, if we note that using Brave Search Premium with an account may make it easier for Brave to correlate queries with specific users.

Done! (I actually used what you wrote here as inspiration since it's already quite succinct.)

**Review by jonaharagon — APPROVED** [review]
Thanks for making the change! LGTM

**Review by xe-3 — APPROVED** [review]

**Comment by ShivanKaul** [comment]
For Brave Search, this statement is inaccurate:

> If you use Brave Search while logged in to a Premium account, there is a risk of Brave correlating search queries with your account.

Premium services in Brave (including Search Premium) are explicitly designed to not associate user activity with payment. We use [Privacy Pass](https://datatracker.ietf.org/wg/privacypass/about/) to accomplish this. See our doc on this [here](https://github.com/brave/brave-core/blob/master/docs/premium_account_privacy.md). All of this code is open-source. The doc I linked also has pointers to the code.

**Pull request merged**
