### PR TITLE
Remove Bromite

### PR DESCRIPTION
**Pull request by matchboxbananasynergy**
Remove Bromite and recommend Brave for Android instead, as Bromite has a trend of being behind in updates.

https://github.com/privacyguides/privacyguides.org/discussions/1512

### CODE REVIEW

**Comment by d4rklynk** [comment]
Where's your Brave recommendation ?

**Comment by matchboxbananasynergy** [comment]
> Where's your Brave recommendation ?

added

**Comment by dngray** [comment]
> > Where's your Brave recommendation ?

> added

I asked for this to be moved to a separate https://github.com/privacyguides/privacyguides.org/pull/1520

It does look like we will have to do this. A requirement we have for all web browsers is that they not fall out of sync with upstream in regard to security updates. It's one of the reasons we've not recommended many of the Firefox forks.

Unfortunately for Bromite, this isn't the first time https://github.com/privacyguides/privacyguides.org/discussions/59#discussioncomment-2099847. While we understand that a lot of work goes into a project like this we do have to put our reader's interests first.

**Review by dngray — APPROVED** [review]

**Comment by flexagoon** [comment]
@Mohamad20ZX yes it does

**Pull request merged**
