### PR TITLE
Add warning to avoid third-party extensions on Brave

### PR DESCRIPTION
**Pull request by d4rklynk**
I think adding UBO on Brave is close to useless because it would be redundant with **Shield** feature of the browser.

I'm not sure about my syntax of my sentences though as english isn't my native language.
Please reconsider my grammar, vocabulary and the syntax if you'll agree to merge this.

### CODE REVIEW

**Review by lx-is — COMMENTED** [review]
uBlock is only explicitly mentioned under the extensions heading for Firefox, so I think it's already pretty clear. That said, it wouldn't hurt to have a small notice; I do think the use of an admonition here is a bit too much.

Maybe an annotation under the shields heading would be a better fit.

**Comment by d4rklynk** [comment]
I think we should let the small notice under the Brave Box, because if someone is used to install UBO on Chrome or FF, and check just PG for alternative, he wuld see directly that he shouldn't use UBO.
IMHO

**Comment by d4rklynk** [comment]
But I agree that the admonition is probably too much

**Comment by d4rklynk** [comment]
I changed it to a title instead of a box

**Comment by lx-is** [comment]
I put the notice under the extensions category. This way, it applies to all third-party extensions and not uBO specifically.

**Review by lx-is — APPROVED** [review]

**Pull request merged**
