### PR TITLE
Remove 7zip

### PR DESCRIPTION
**Pull request by tommytran732**
7ZIP encryption is known to be horrible and should not be recommended as a tool at any cost.

Here are a few links:
https://www.redhat.com/sysadmin/encrypting-decrypting-7zip
https://zdnet.com/article/severe-7-zip-vulnerabilities-cause-top-security-software-tools-patch-panic/
https://www.cvedetails.com/vulnerability-list/vendor_id-9220/7-zip.html

### CODE REVIEW

**Review by Mikaela — APPROVED** [review]
👍🏻  7Zip wouldn't occur to me if I was asked about file encryption software.

**Review by freddy-m — APPROVED** [review]
LGTM

**Comment by Mikaela** [comment]
> Merging is blocked
> The base branch requires all commits to be signed. 

I am not aware of such restriction being something GitHub supports and imagine it is due to you having enabled vigilant mode while not actually signing your commit, @tommytran732

**Comment by tommytran732** [comment]
> > Merging is blocked
> > The base branch requires all commits to be signed.
> 
> I am not aware of such restriction being something GitHub supports and imagine it is due to you having enabled vigilant mode while not actually signing your commit, @tommytran732

I disabled it. It does not work with Github VScode anyways. It still looks like it's blocked though - I think it has to do with PG's setting or something.

It's kind of weird because dngray merged my pull requests just fine earlier today.

**Comment by tommytran732** [comment]
Could you check your settings?

image

**Comment by tommytran732** [comment]
This is quite annoying because GitHub's VSCode signing is broken at the moment.

**Comment by Mikaela** [comment]
> Could you check your settings?

Which settings are these? If they are settings for this repository, then I don't have access (at least the mobile web doesn't expose them and navigating to /settings gives me 404).

I have no idea how @dngray has done it, maybe they have some sort of override and access to those settings.

If we require signed commits to main, I think that is either a mistake or the team should be instructed whether we are allowed to push there by hand and I imagine some team members would need instruction on how to do that.

**Comment by dngray** [comment]
> I have no idea how @dngray has done it, maybe they have some sort of override and access to those settings.

Yes, I am able to force it. but I rather not do that. I might do it for this case though.

**Review by dngray — APPROVED** [review]

**Comment by FireMasterK** [comment]
> 7ZIP encryption is known to be horrible and should not be recommended as a tool at any cost

Yeah guys, AES-256 is horrible shouldn't be recommended despite still being recommended by the NIST, and doesn't have known weaknesses (I'm being sarcastic obviously)

**Comment by TheFrenchGhosty** [comment]
@tommytran732 @dngray @Mikaela 

>7ZIP encryption is known to be horrible

It's AES. It's literally the encryption standard.


>and should not be recommended as a tool at any cost.

What?

Have you read the URLs you linked (the zdnet article literally said that it's fixed)? Those are minor vulnerabilities privacy-wise that can't be used by anyone without access to the machine/file (and if they do, it's too late, no matter the software). 7zip/p7zip encryption is 100% perfectly fine.

--- 

Seriously guys, I just checked 5 of the recent PRs and it's all removal of perfectly good tools. 

As I was telling you guys a while ago: "I'm not expecting the new branding/management to change that." ( https://github.com/privacyguides/privacyguides.org/pull/247#issuecomment-962653505 ) the new branding/management already did more bad decision than the previous one in 2 years.

**Comment by Mikaela** [comment]
I have left the team, am on sick leave and have no idea what Privacy Guides is doing nowadays, @TheFrenchGhosty, but I hope the team is able to address your concerns.

* https://mikaela.info/blog/english/2021/11/23/leaving-privacyguides.html

**Comment by TheFrenchGhosty** [comment]
@Mikaela Thank you for the insight, guess this proves my point.

Sorry things went that way.

**Comment by TheFrenchGhosty** [comment]
@Mikaela I don't know if you care, or not, but I started writing an actual good list myself: https://wiki.pussthecat.org/privacy-guide.md (sorry it's on WikiJS for now, so it requires JavaScript).

If you want to discuss it, just hop on Matrix.

**Comment by tommytran732** [comment]
> @tommytran732 @dngray @Mikaela
> 
> > 7ZIP encryption is known to be horrible
> 
> It's AES. It's literally the encryption standard.
> 
> > and should not be recommended as a tool at any cost.
> 
> What?
> 
> Have you read the URLs you linked (the zdnet article literally said that it's fixed)? Those are minor vulnerabilities privacy-wise that can't be used by anyone without access to the machine/file (and if they do, it's too late, no matter the software). 7zip/p7zip encryption is 100% perfectly fine.
> 
> Seriously guys, I just checked 5 of the recent PRs and it's all removal of perfectly good tools.
> 
> As I was telling you guys a while ago: "I'm not expecting the new branding/management to change that." ( [#247 (comment)](https://github.com/privacyguides/privacyguides.org/pull/247#issuecomment-962653505) ) the new branding/management already made more bad decisions than the previous one in 2 years.

Something being AES-256 doesn't make it magically secure if they fuck up the implementations.

**Comment by dngray** [comment]
> Seriously guys, I just checked 5 of the recent PRs and it's all removal of perfectly good tools.

We're not recommending sub optimal tools. If you actually read the reasons for removal then you wouldn't be saying they are "perfectly good".

**Comment by TheFrenchGhosty** [comment]
>Something being AES-256 doesn't make it magically secure if they fuck up the implementations.

And they didn't "fuck up the implementations".

>A cursory look at it shows plenty of misinformation and conspiracy.

Sure. If you say so.

**Comment by dngray** [comment]
> And they didn't "fuck up the implementations".

How do you know? Have you audited the source. I think not.

> Sure. If you say so.

yes for a start the BS about PM. They complied with a court order, nothing dodgy about that. Literally any email provider in any country would do the same.

**Pull request merged**
