### PR TITLE
update!: Create separate page for Pastebins

### PR DESCRIPTION
**Pull request by redoomed1**
Changes proposed in this PR:

- Create a separate recommendation page for pastebins
  - This PR kicks off a multipart effort to address #2596 
  - No changes to the content ported from the Productivity Tools page
  - Changes for the new recommendation page
    - Added page cover: a photo by Chris Ried at https://unsplash.com/photos/a-computer-screen-with-a-bunch-of-code-on-it-ieic5Tq8YMk; any suggestions for alternative page covers are welcome!
    - Added `content-paste` Material Design sidebar icon
    - Added page introduction and one-sentence description
- Add Pastebins section in `tools.md` and move PrivateBin entry to it
- Delete "Paste services" section from the Productivity Tools page

This is my first PR that involves an image upload, so I welcome any feedback in this department! I went over https://www.privacyguides.org/en/meta/uploading-images, but there isn't any guidance on WebP images, which is the preferred format for cover images.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Comment by redoomed1** [comment]
@jonaharagon Thoughts on the cover photo and material icon? I'm pinging specifically you since I know that you made a [suggestion in another PR](https://github.com/privacyguides/privacyguides.org/pull/2409#issuecomment-1995075794) on sourcing images.

**Comment by redoomed1** [comment]
Slight issue: the photos from Unsplash that I wanted to use for the Pastebins page cover are all .jpg files. When trying to run [the command to optimize PNG (recommended on the Privacy Guides "About" page)](https://www.privacyguides.org/en/meta/uploading-images/#png) on `pastebins.png`, it returns this error: `Error: JPEG decoding is not supported`.

**Comment by redoomed1** [comment]
How I went about optimizing the Unsplash image linked in my initial post:

1. Download it as a .jpg file
2. Use [`cwebp`](https://developers.google.com/speed/webp/docs/cwebp) to convert it to a WebP file by running `cwebp -size 300000 [image-name].jpg -o pastebins.webp`

[`-size`](https://developers.google.com/speed/webp/docs/cwebp#lossy_options) specifies target size in bytes. I set it to 300,000 bytes (300 KB) because, of all the cover images on the site, the one for the Desktop Browsers page is the largest at 305 KB.

**Comment by jonaharagon** [comment]
Good note, we should probably document WebP optimization. IIRC all the existing images were a pre-set quality level but I don't remember what that setting was.

**Review by dngray — APPROVED** [review]

**Pull request merged**
