### PR TITLE
fix: Move Hardware Guide to Knowledge Base

### PR DESCRIPTION
**Pull request by redoomed1**
Changes proposed in this PR:

- Move the recently published Hardware Guide to the Knowledge Base
  - I'm not sure what happened to the commit mentioned [here](https://github.com/privacyguides/privacyguides.org/pull/2268#pullrequestreview-2190058447); regardless, the entry currently in `mkdocs.yml` is not consistent with the rest in the "Recommendations" section. In my opinion, this page being in the KB makes a lot of sense since it doesn't offer tool recommendations in the same way that other pages (like any of the recently split Android pages) do.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Comment by redoomed1** [comment]
I do think that, somewhere in the Hardware section of the Recommended Tools, there should be a link to this KB article, in the same way that the recommendation pages for Password Managers, VPNs, and MFA tools all feature a link back to their respective KB article.

**Comment by jonaharagon** [comment]
This is unfortunate, a version was merged that I've never reviewed or approved :(

Probably have to look through the hardware PR to check for other unknown changes.

**Review by jonaharagon — APPROVED** [review]
As far as I can tell the change you mentioned from e037fd7d6620de0dc6c5f9c08aab5393099fd1d3 is the only change that was missing in the PR...

**Comment by dngray** [comment]
That might have been my mistake.

**Review by dngray — APPROVED** [review]

**Pull request merged**
