### PR TITLE
Remove Posteo and updated criteria

### PR DESCRIPTION
**Pull request by tommytran732**
Not having a proper DMARC/ARC record is a pretty serious security issue, so I think this one is a no brainer.

### CODE REVIEW

**Review by freddy-m — APPROVED** [review]
LGTM

**Review by hook9 — APPROVED** [review]

**Comment by tommytran732** [comment]
My bad, I realized it should be in security instead of privacy,

**Comment by freddy-m** [comment]
Is this @hook9's first ever review? Awesome

**Review by jonaharagon — APPROVED** [review]

**Review by dngray — APPROVED** [review]

**Comment by jonaharagon** [comment]
FYI (src: [posteo.de](https://posteo.de/site/postmaster))

> However, we have a DMARC "none" policy for Posteo email domain names, since DMARC is currently not recommended for mailbox providers. Outbound DMARC policies are primarily "best-suited for transactional emails and semi-transactional emails" (dmarc.org [FAQ](https://dmarc.org/wiki/FAQ#Why_doesn.27t_.28major_mailbox_provider.29_publish_a_DMARC_record.3F)). At the present, DMARC has implications which do not meet customers' individual use of email.

**Comment by tommytran732** [comment]
> FYI (src: [posteo.de](https://posteo.de/site/postmaster))
> 
> > However, we have a DMARC "none" policy for Posteo email domain names, since DMARC is currently not recommended for mailbox providers. Outbound DMARC policies are primarily "best-suited for transactional emails and semi-transactional emails" (dmarc.org [FAQ](https://dmarc.org/wiki/FAQ#Why_doesn.27t_.28major_mailbox_provider.29_publish_a_DMARC_record.3F)). At the present, DMARC has implications which do not meet customers' individual use of email.

I will DM you and do some testing.

**Comment by dngray** [comment]
It's worth mentioning major email senders like google, microsoft, yahoo, fastmail, zendesk sendgrid,  (and some other smaller ones glesys.se, wp.pl) etc, all support [Authenticated Received Chain](https://en.wikipedia.org/wiki/Authenticated_Received_Chain) which seems to address the mailing list problem.

It's evaluated by rspamd also has an [arc](https://rspamd.com/doc/modules/arc.html) module that I've seen used in various emails.

If we look at our other recommendations, protonmail, mailbox.org, disroot, startmail, tutanota, ctemplar, they all have DMARC policies set to either reject/quarantine.

**Comment by TheFrenchGhosty** [comment]
@tommytran732 @freddy-m So let me get this straight: you removed Posteo, one of the most privacy friendly email provider, but kept Protonmail, an email provider, that is at best sketchy, at worse a honeypot, with weird funding sources... because Posteo doesn't have DMARC... something that is basically meaningless for end users. Just WOW.

**Comment by tommytran732** [comment]
> @tommytran732 @freddy-m So let me get this straight: you removed Posteo, one of the most privacy friendly email provider, but kept Protonmail, an email provider, that is at best sketchy, at worse a honeypot, with weird funding sources... because Posteo doesn't have DMARC... something that is basically meaningless for end users. Just WOW.

1. So do you like having your email spoofed because of the lack of DMARC?
2. What makes Posteo any more private than ProtonMail
3. Stop spreading FUD. Really.

**Comment by dngray** [comment]
> Stop spreading FUD. Really.

Exactly. I'm getting the feeling @TheFrenchGhosty has some agenda. They've popped up out of nowhere and literally have just commented on our removals without reading or understanding the reasons.

**Comment by TheFrenchGhosty** [comment]
>Exactly. I'm getting the feeling @TheFrenchGhosty has some agenda.

Ah yes, if I disagree with you I have an agenda, makes sense.

Bye.

**Pull request merged**
