### PR TITLE
Revamping the Encrypted DNS page

### PR DESCRIPTION
**Pull request by DeiAsPie**
## Resolves: Issues considered solved as per my knowledge:
- #572    
- #561  
- #543    
- #321 
 
## Recommendations considered:
- #556 
- #593 
- #197 
- #567 
- #241 
- #252 
- #111 

## Changes made:
- Added [when to use dns](https://github.com/dngray/encrypted-dns/blob/main/dns.svg) image by @dngray 
- Removed UncensoredDNS
- Added MullvadDNS
- Removed columns for Qname minimization and DNSSEC
- Added column for ECS
- Removed the warning of Android DNS being ineffective when using VPN
- Added definitions of Qname Minimization, DNSSEC and ECS
- Replaced Nebulo by a better project [RethinkDNS](https://rethinkdns.com/)
- Removed third party clients and suggest using native implementations instead

## Effected page: 
https://privacyguides.org/providers/dns/

### CODE REVIEW

**Comment by tommytran732** [comment]
Hey is there anything more you want to add to the PR before I make my own changes to it?

Ideally I would want to remove all of these custom DNS clients and just refer the user to the OS's documentation, and I want to add a section explaining the ineffectiveness of encrypted DNS.

**Comment by DeiAsPie** [comment]
I don't have anything on my mind to add right now. If you want me to do something, would be happy to help.

Go ahead make the changes you like.

**Comment by DeiAsPie** [comment]
I think let Rethink stay there for the situation in which someone has a Xiaomi phone which doesn't have the Private DNS option available to the user.

**Comment by freddy-m** [comment]
I like the flow chart, however I feel as though it sits oddly on the page @dngray

**Comment by dngray** [comment]
> I like the flow chart, however I feel as though it sits oddly on the page @dngray

it needs to be in it's own division and wrapped around text that actually explains why it is, i'll probably get to that after working on current pages in queue.

**Comment by dngray** [comment]
Regarding https://github.com/privacyguides/privacyguides.org/pull/575/commits/e42177a9bd89ebeb35cc6e1f230c986c3252785f

I just think it won't be enabled by default [1833144](https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1833144), [1990006](https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1990006) which means it might make sense for us to provide instruction on how to enable it.

**Comment by dngray** [comment]
Regarding https://github.com/privacyguides/privacyguides.org/pull/575/commits/e42177a9bd89ebeb35cc6e1f230c986c3252785f

It won't be enabled by default [1833144](https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1833144), [1990006](https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1990006) which means it might make sense for us to provide instruction on how to enable it. If you look at the code change it was literally 4 lines:

```diff
- inline bool isDoHEnabled() {
-    // STOPSHIP(b/200763585): clean up it before T shipping.
-     static bool isAtLeastT = android::modules::sdklevel::IsAtLeastT();
-     if (isAtLeastT) return 1;
-     return android::net::Experiments::getInstance()->getFlag("doh", 0);
- }
```

Which doesn't mean the whole implementation was ripped out or anything.

**Comment by dngray** [comment]
I've merged this into a DNS branch on the main repo.

**Pull request merged**
