### PR TITLE
Minor update to app description

### PR DESCRIPTION
**Pull request by sh-dv**
## Description
Hey, i am the developer of Hat.sh.
I request the change of some minor information in the page because in V2 we changed the algorithm and added many features.

### Affected page
[https://privacyguides.org/software/productivity/#encrypt](https://privacyguides.org/software/productivity/#encrypt)

### Requested Changes : 
- the use of the word `client-side` instead of `serverless` is more accurate and appropriate.
- the removal of `using the AES-256-GCM algorithm` because the app currently uses `XChaCha20-Poly1305` (v2).
- instead of writing `downloaded and run offline`, i think the word `selfhosted` is enough.

Thanks and good luck!

### CODE REVIEW

**Review by jonaharagon — APPROVED** [review]
Fair enough, thanks!

**Review by Mikaela — APPROVED** [review]
I am not seeing what exactly changed since the previous review.

**Comment by sh-dv** [comment]
Just wondering why is this taking so long ?

**Comment by Mikaela** [comment]
I apologise for the delay, we have a small team with people having other life and various other stress in addition to the unpaid volunteering on PrivacyGuides and everything needs at least two people to approve it before merging.

**Comment by sh-dv** [comment]
Understood, no problem.

**Review by freddy-m — APPROVED** [review]
Sorry, think I accidentally sent this to the rereview queue. Welp

**Pull request merged**
