### PR TITLE
Adding ControlD to list of DNS providers.

### PR DESCRIPTION
**Pull request by wintr-**
Resolves: Lack of ControlD on the DNS Providers list ;)

Thanks so much for the work on the guide.

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
why u closed this PR https://github.com/privacyguides/privacyguides.org/pull/544 and created a new one?

**Comment by wintr-** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc The checks were telling me that my PR could not be merged because it was not signed. I was having issues getting through the signing workflow when rebasing, so figured I would just start fresh. Apology if that's problematic.

**Review by tommytran732 — APPROVED** [review]
LGTM

**Review by freddy-m — APPROVED** [review]
I'll approve this, but next time please open a discussion before submitting a PR, thanks.

**Pull request merged**
