### PR TITLE
Remove Mojeek

### PR DESCRIPTION
**Pull request by lx-is**
This isn't yet approved—a discussion still needs to take place. I'll post the link to the discussion here once it's created.

The general idea discussed in Matrix is that, while Mojeek is a private option, it does not offer a great search experience. Brave Search is private too, although unfortunately has "Anonymous usage metrics" enabled by default. It, however, offers a much better searching experience. At the end of the day, you still have to trust Brave that they'll respect their policy, but, considering we recommend the Brave Browser, it would be inconsistent to not trust their search policy as well.

### CODE REVIEW

**Comment by dngray** [comment]
I'm not opposed to this, would need to look at how brave search privacy policy compares, and what it's search quality is like.

Mojeek is pretty bad experience.

**Comment by jonaharagon** [comment]
> a discussion still needs to take place.

*Two* discussions actually need to take place: removing Mojeek, and listing Brave Search. Ideally they'd be separate PRs tbh.

**Comment by jonaharagon** [comment]
Ok I wanted to give Mojeek some benefit of the doubt, but results _are_ pretty bad lol

Screenshot 2022-05-19 at 12 58 52@2x

**Comment by freddy-m** [comment]
@jonaharagon and Brave Search seems decidedly better...
Screenshot 2022-05-19 at 19 51 12

**Review by dngray — APPROVED** [review]

**Review by dngray — CHANGES_REQUESTED** [review]
Going to split into two separate PRs

**Review by dngray — APPROVED** [review]

**Comment by xrat** [comment]
mojeek-search-privacy-guides20220522

**Pull request merged**
