### PR TITLE
Add back PeerTube, Invidious, remove LBRY

### PR DESCRIPTION
**Pull request by julianfairfax**
## Description

#274 removed PeerTube under the grounds of it not providing a way to have a private subscription list, and replaced it with LBRY, [a platform that condones and promotes misinformation and nazi content](https://en.wikipedia.org/wiki/LBRY#Moderation). It also removed Invidious, confusing many, and accomplishing little.

This PR adds back PeerTube on the grounds of it being the best technical implementation of an alternative to YouTube despite the private subscription list, removes LBRY due to it's objectively deplorable moderation team, and reinstates Invidious as a viable frontend to YouTube on the web. Both PeerTube and Invidious can be self-hosted, alleviating supposed issues, whereas LBRY may be possible to self-host, but this isn't common practice.

### CODE REVIEW

**Review by Mikaela — CHANGES_REQUESTED** [review]
I was not around to review #274, while I agree with your concerns on LBRY and while I agree with your concerns, I have some issues with this PR as well:

* The application categories are messed up. First there is an application FreeTube for desktop, then PeerTube web service, NewPipe for Android and finally Invidious for web. Could you arrange them and maybe even add headings to distinguish mobile, desktop and web?
  * Additionally I wonder if PeerTube has a PWA?
* I think PeerTube shares what you watch to other peers simultaneously (which is one of the points it exists), I think that needs a warning label. While PeerTube may not be within the scope-of-site (I am not sure where that is currently being discussed), I think it's important for diversity of the internet.
 * #274 had a concern on Invidious not being a privacy feature for sending your IP back to Google by default, I see you added that as a note. Could you change it as a warning label instead?

**Comment by dngray** [comment]
> #274 removed PeerTube under the grounds of it not providing a way to have a private subscription list, and replaced it with LBRY, [a platform that condones and promotes misinformation and nazi content](https://en.wikipedia.org/wiki/LBRY#Moderation). It also removed Invidious, confusing many, and accomplishing little.

While this isn't ideal, we try to keep services and recommendations in scope to how they relate to privacy and security. You'll find Nazi content on just about anything (Tor, Freenet, IPFS etc) that isn't centralized with huge amounts of analytics and machine learning constantly applying a defined criteria. To note there's only a few companies capable of doing that at large scale.

> This PR adds back PeerTube on the grounds of it being the best technical implementation of an alternative to YouTube despite the private subscription list

The thing about PeerTube is there is nothing inherently private about it. An instance operator can see whatever you're doing and apply whatever adtech/analytics they want. Further, a lot of PeerTube instances don't even have a clearly defined privacy policy.

> reinstates Invidious as a viable frontend to YouTube on the web.

It's worth noting that Invidious isn't private either. It forwards all requests through to googlevideo.com unless the `&local=true` parameter is set on the video, ie: https://vid.puffyan.us/watch?v=nF3d8v6hs2Q&local=true to my knowledge instances don't do this by default. That being said I did mention [here](https://github.com/privacyguides/privacyguides.org/discussions/341#discussioncomment-1674398) that it is highly likely that any analytics on youtube is going to be on [youtube.com](youtube.com) or [google.com](google.com), and using invidious does not make requests to these domains.

> Both PeerTube and Invidious can be self-hosted, alleviating supposed issues, whereas LBRY may be possible to self-host, but this isn't common practice.

Self hosting also requires bandwidth and a server, something a lot of users don't have or want to run.

However that being said I do believe we *could* split that video-streaming page into two sections.

1. Services which host content (peertube, lbry)
2. Services which are frontends to youtube (invidious, freetube, newpipe).

If we do this we should have a warning:

1. Invidious is not private and forwards all video requests to [googlevideo.com](googlevideo.com) (unless you add `&local=true` to the URL
2. Invidious/PeerTube: If your threat model requires privacy you should use a VPN or Tor (some invidious instances do allow for .onion access so that is something that "enhances privacy"

**Comment by julianfairfax** [comment]
> I was not around to review #274, while I agree with your concerns on LBRY and while I agree with your concerns, I have some issues with this PR as well:
> 
>     * The application categories are messed up. First there is an application FreeTube for desktop, then PeerTube web service, NewPipe for Android and finally Invidious for web. Could you arrange them and maybe even add headings to distinguish mobile, desktop and web?
>       
>       * Additionally I wonder if PeerTube has a PWA?
> 
>     * I think PeerTube shares what you watch to other peers simultaneously (which is one of the points it exists), I think that needs a warning label. While PeerTube may not be within the scope-of-site (I am not sure where that is currently being discussed), I think it's important for diversity of the internet.
> 
>     * #274 had a concern on Invidious not being a privacy feature for sending your IP back to Google by default, I see you added that as a note. Could you change it as a warning label instead?

I attempted to make those changes as you asked:

- I've reordered them and added the heading like you asked.
  - I don't know.
- I added that as a warning label like you asked.
- I added that as a warning label like you asked.

**Comment by julianfairfax** [comment]
> > #274 removed PeerTube under the grounds of it not providing a way to have a private subscription list, and replaced it with LBRY, [a platform that condones and promotes misinformation and nazi content](https://en.wikipedia.org/wiki/LBRY#Moderation). It also removed Invidious, confusing many, and accomplishing little.
> 
> While this isn't ideal, we try to keep services and recommendations in scope to how they relate to privacy and security. You'll find Nazi content on just about anything (Tor, Freenet, IPFS etc) that isn't centralized with huge amounts of analytics and machine learning constantly applying a defined criteria. To note there's only a few companies capable of doing that at large scale.
> 
> > This PR adds back PeerTube on the grounds of it being the best technical implementation of an alternative to YouTube despite the private subscription list
> 
> The thing about PeerTube is there is nothing inherently private about it. An instance operator can see whatever you're doing and apply whatever adtech/analytics they want. Further, a lot of PeerTube instances don't even have a clearly defined privacy policy.
> 
> > reinstates Invidious as a viable frontend to YouTube on the web.
> 
> It's worth noting that Invidious isn't private either. It forwards all requests through to googlevideo.com unless the `&local=true` parameter is set on the video, ie: https://vid.puffyan.us/watch?v=nF3d8v6hs2Q&local=true to my knowledge instances don't do this by default. That being said I did mention [here](https://github.com/privacyguides/privacyguides.org/discussions/341#discussioncomment-1674398) that it is highly likely that any analytics on youtube is going to be on [youtube.com](youtube.com) or [google.com](google.com), and using invidious does not make requests to these domains.
> 
> > Both PeerTube and Invidious can be self-hosted, alleviating supposed issues, whereas LBRY may be possible to self-host, but this isn't common practice.
> 
> Self hosting also requires bandwidth and a server, something a lot of users don't have or want to run.
> 
> However that being said I do believe we _could_ split that video-streaming page into two sections.
> 
>     1. Services which host content (peertube, lbry)
> 
>     2. Services which are frontends to youtube (invidious, freetube, newpipe).
> 
> 
> If we do this we should have a warning:
> 
>     1. Invidious is not private and forwards all video requests to [googlevideo.com](googlevideo.com) (unless you add `&local=true` to the URL
> 
>     2. Invidious/PeerTube: If your threat model requires privacy you should use a VPN or Tor (some invidious instances do allow for .onion access so that is something that "enhances privacy"

The problem here is that LBRY is centralized and are actively permitting it. Tor, Freenet, IPFS are not. I believe it's possible to self-host LBRY, but it is not common practice. 

There's nothing inherently private about any service then. A Mastodon instance operator can see whatever you're doing and apply whatever adtech/analytics they want. And they don't have to have a clearly defined privacy policy.

It doesn't matter if users will self-host, it matters that they can and do. No one, as fair as I know actually self-hosts LBRY.

**Comment by Mikaela** [comment]
I would like to point out that PrivacyGuides.org policy is to have two team members review software additions or removals before they are posted on main/master/the-site. https://github.com/privacyguides/privacyguides.org/pull/274 did not follow this policy that can be seen on GitHub and I was available and reading the team room also during my absense.

* * * * *
* 
> While this isn't ideal, we try to keep services and recommendations in scope to how they relate to privacy and security. You'll find Nazi content on just about anything (Tor, Freenet, IPFS etc) that isn't centralized with huge amounts of analytics and machine learning constantly applying a defined criteria. To note there's only a few companies capable of doing that at large scale.

Do they promote it actively or is the first thing coming to your mind on hearing them "misinformation"? In Finland their sibling Tokentube is all antivax propaganda.

> The thing about PeerTube is there is nothing inherently private about it. An instance operator can see whatever you're doing and apply whatever adtech/analytics they want. Further, a lot of PeerTube instances don't even have a clearly defined privacy policy.

We are recommending other software and services which have privacy issues such as #50 and as far as I am aware, Matrix homeservers aren't particularly great in publishing privacy policies either. I would like to point out that the PR is linking directly to Invidious homepage and not to a particular instance.

> It's worth noting that Invidious isn't private either. It forwards all requests through to googlevideo.com unless the &local=true parameter is set on the video, ie: https://vid.puffyan.us/watch?v=nF3d8v6hs2Q&local=true to my knowledge instances don't do this by default. That being said I did mention here that it is highly likely that any analytics on youtube is going to be on youtube.com or google.com, and using invidious does not make requests to these domains.

Warning label.

> Self hosting also requires bandwidth and a server, something a lot of users don't have or want to run.

:+1:

> However that being said I do believe we could split that video-streaming page into two sections.

I somewhat agree.

> Services which host content (peertube, lbry)
> Services which are frontends to youtube (invidious, freetube, newpipe).

While I view Individious as a frontend to YouTube, I would consider FreeTube and NewPipe as YouTube clients considering one is desktop app and another is an Android app.

> If we do this we should have a warning:

> Invidious is not private and forwards all video requests to googlevideo.com (unless you add &local=true to the URL
> Invidious/PeerTube: If your threat model requires privacy you should use a VPN or Tor (some invidious instances do allow for .onion access so that is something that "enhances privacy"

Maybe we could also mention good old mpv and youtube-dl that can be used through Tor for these users?

**Review by Mikaela — APPROVED** [review]
Thank you for making the changes. While I think the page could look better, I have no idea how I would start doing that and I consider this to be in a better condition than some other pages (that may have content removals saying the new information will be added in the future).

**Comment by tommytran732** [comment]
1. I agree with dngray here. Nazis can be found anywhere, even on Facebook, Youtube, Google. Just because they take advantage of LBRY's system, it doesn't mean LBRY is made for Nazis. Are we going to let a bunch of scumbags ruin a great service?

2. LBRY is not even centralized. They can't even control the network, just like Tor or Freenet. Nazis getting onto the platform is not a real problem to delist them imo,

I am totally not in favor of removing LBRY.

**Comment by julianfairfax** [comment]
> 1. I agree with dngray here. Nazis can be found anywhere, even on Facebook, Youtube, Google. Just because they take advantage of LBRY's system, it doesn't mean LBRY is made for Nazis. Are we going to let a bunch of scumbags ruin a great service?
> 

Facebook, YouTube, and Google remove them. They don't take advantage of LBRY's system. LBRY actively refuses to do anything about them. It practically is made for nazis. And the scumbags ruining the service are the ones running it.
>     2. LBRY is not even centralized. They can't even control the network, just like Tor or Freenet. Nazis getting onto the platform is not a real problem to delist them imo,
> 

They can at the very least control the clients, which they refuse to do. And everything goes through their centralized server.
> 
> I am totally not in favor of removing LBRY.

And I'm totally not in favor of supporting platforms that practically support nazis.

**Comment by tommytran732** [comment]
There is nothing that inherently makes Invidious or Piped private. There is nothing that makes PeerTube inherently private. In fact, what difference does it make if you use a VPN + YouTube instead of a VPN + Invidious? Putting Invidious there makes no sense to recommend it there if it does not serve any purpose for privacy.

**Review by dngray — CHANGES_REQUESTED** [review]
At very least requires changes https://github.com/privacyguides/privacyguides.org/pull/356#issuecomment-974866065

**Comment by julianfairfax** [comment]
> There is nothing that inherently makes Invidious or Piped private. There is nothing that makes PeerTube inherently private. In fact, what difference does it make if you use a VPN + YouTube instead of a VPN + Invidious? Putting Invidious there makes no sense to recommend it there if it does not serve any purpose for privacy.

What makes any other service here private? If the argument is that the instance can do whatever they want, that applies to anything.

**Comment by julianfairfax** [comment]
> At very least requires changes [#356 (comment)](https://github.com/privacyguides/privacyguides.org/pull/356#issuecomment-974866065)

What are the changes you're referring to?

> However that being said I do believe we could split that video-streaming page into two sections.
> 
>     Services which host content (peertube, lbry)
>     Services which are frontends to youtube (invidious, freetube, newpipe).
>
> If we do this we should have a warning:
> 
>     Invidious is not private and forwards all video requests to googlevideo.com (unless you add &local=true to the URL
>     Invidious/PeerTube: If your threat model requires privacy you should use a VPN or Tor (some invidious instances do allow for .onion access so that is something that "enhances privacy"

These?

**Comment by tommytran732** [comment]
> > 1. I agree with dngray here. Nazis can be found anywhere, even on Facebook, Youtube, Google. Just because they take advantage of LBRY's system, it doesn't mean LBRY is made for Nazis. Are we going to let a bunch of scumbags ruin a great service?
> 
> Facebook, YouTube, and Google remove them. They don't take advantage of LBRY's system. LBRY actively refuses to do anything about them. It practically is made for nazis. And the scumbags ruining the service are the ones running it.
> 
> > ```
> > 2. LBRY is not even centralized. They can't even control the network, just like Tor or Freenet. Nazis getting onto the platform is not a real problem to delist them imo,
> > ```
> 
> They can at the very least control the clients, which they refuse to do. And everything goes through their centralized server.
> 
> > I am totally not in favor of removing LBRY.
> 
> And I'm totally not in favor of supporting platforms that practically support nazis.

No they are not. You cannot control a decentralized system. If Nazis start uploading torrents, is it the torrent network's problem? Because the design of the LBRY network and the torrent network are near identical.If I make a client that streams content of of torrent and people happen to stream Nazi content, is it my problem?

**Comment by julianfairfax** [comment]
> > > 1. I agree with dngray here. Nazis can be found anywhere, even on Facebook, Youtube, Google. Just because they take advantage of LBRY's system, it doesn't mean LBRY is made for Nazis. Are we going to let a bunch of scumbags ruin a great service?
> > 
> > 
> > Facebook, YouTube, and Google remove them. They don't take advantage of LBRY's system. LBRY actively refuses to do anything about them. It practically is made for nazis. And the scumbags ruining the service are the ones running it.
> > > ```
> > > 2. LBRY is not even centralized. They can't even control the network, just like Tor or Freenet. Nazis getting onto the platform is not a real problem to delist them imo,
> > > ```
> > 
> > 
> > They can at the very least control the clients, which they refuse to do. And everything goes through their centralized server.
> > > I am totally not in favor of removing LBRY.
> > 
> > 
> > And I'm totally not in favor of supporting platforms that practically support nazis.
> 
> No they are not. You cannot control a decentralized system. If Nazis start uploading torrents, is it the torrent network's problem? Because the design of the LBRY network and the torrent network are near identical.If I make a client that streams content of of torrent and people happen to stream Nazi content, is it my problem?

This isn't a question of capability. They are saying they won't do anything. While this obviously applies they could do something, that's irrelevant. The LBRY staff condone this content. They condone nazis.

**Comment by tommytran732** [comment]
> 

The Matrix comparison is a very bad IMO. Matrix home servers are not to be trusted. You should always assume that your metadata is collected. You should never assume a Matrix home server is safe, just because it appears so in the privacy policy. 

The only guarantee you are ever getting with Matrix is the encryption of your messages. The main appealing aspect of Matrix (and especially element) is that you can have end to end encryption for groups, end to end encryption for 1:1 messages, and end to end encryption for 1:1 video calls. 

However, as you can see here, Matrix itself does provide a privacy benefit (end to end encryption), and we are specifically recommending the Element client. We don't recommend the Matrix network as a whole, because there is nothing inherent about the network that makes it private. We don't even recommend Matrix home servers either, because the only thing you have guarantees for is the fact that your messages are encrypted.

On the other hand, Invidious provides no apparent benefits for privacy. It is a shifting trust situation (and only if proxying is on). The same thing is with PeerTube - if there is a desktop client that helps preserving privacy, awesome. There is currently one in development (Cuttlefish). On Android, NewPipe is a great client for PeerTube, and it is already a recommended client. However, it makes no sense to recommend PeerTube as a network, because there is nothing inherently private about it.

**Comment by dngray** [comment]
> The problem here is that LBRY is centralized and are actively permitting it. Tor, Freenet, IPFS are not. I believe it's possible to self-host LBRY, but it is not common practice.

No it's not. The LBRY protocol is decentralized. Only the Odysee website is centralized. Furthemore they have a [criteria](https://odysee.com/@OdyseeHelp:b/Community-Guidelines:c)

> Do they promote it actively or is the first thing coming to your mind on hearing them "misinformation"? In Finland their sibling Tokentube is all antivax propaganda.

It's worth noting you'll see plenty of that on PeerTube.

> While I view Individious as a frontend to YouTube, I would consider FreeTube and NewPipe as YouTube clients considering one is desktop app and another is an Android app.

They use the Individious API, which we do clearly say there. They come with the additional benefit of keeping preference data on your device.

> Maybe we could also mention good old mpv and youtube-dl that can be used through Tor for these users?

Maybe (btw that's done with):

```
http_proxy=http://127.0.0.1:8118 mpv --http-proxy=http://127.0.0.1:8118 { youtube url}
```


> Facebook, YouTube, and Google remove them.

They are also centralized platforms with significant resources, and leading in automated learning, and that is a pretty unfair comparison. It's also worth noting that those bad actors have been skirting policies on those platforms for ages.

> And I'm totally not in favor of supporting platforms that practically support nazis.

Fortunately the site is about privacy and security, not nazis.

**Comment by julianfairfax** [comment]
> > The problem here is that LBRY is centralized and are actively permitting it. Tor, Freenet, IPFS are not. I believe it's possible to self-host LBRY, but it is not common practice.
> 
> No it's not. The LBRY protocol is decentralized. Only the Odysee website is centralized. Furthemore they have a [criteria](https://odysee.com/@OdyseeHelp:b/Community-Guidelines:c)
> 
They still control the apps and website. And as they mentioned, they clearly could remove the content there. As they also mentioned, nazi content isn't against their guidelines.

> > Do they promote it actively or is the first thing coming to your mind on hearing them "misinformation"? In Finland their sibling Tokentube is all antivax propaganda.
> 
> It's worth noting you'll see plenty of that on PeerTube.

That's the responsibility of each instance. This is the responsibility of LBRY.
> 
> > While I view Individious as a frontend to YouTube, I would consider FreeTube and NewPipe as YouTube clients considering one is desktop app and another is an Android app.
> 
> They use the Individious API, which we do clearly say there. They come with the additional benefit of keeping preference data on your device.
> 
> > Maybe we could also mention good old mpv and youtube-dl that can be used through Tor for these users?
> 
> Maybe (btw that's done with):
> 
> ```
> http_proxy=http://127.0.0.1:8118 mpv --http-proxy=http://127.0.0.1:8118 { youtube url}
> ```
> 
> > Facebook, YouTube, and Google remove them.
> 
> They are also centralized platforms with significant resources, and leading in automated learning, and that is a pretty unfair comparison. It's also worth noting that those bad actors have been skirting policies on those platforms for ages.
> 

The difference here is that LBRY's policy allows this. Or at least their staff do.
> > And I'm totally not in favor of supporting platforms that practically support nazis.
> 
> Fortunately the site is about privacy and security, not nazis.

And do you want this site to be endorsing nazis? I can't imagine it would be a good look to promote this platform despite its, what is at the very least, controversy.

**Comment by julianfairfax** [comment]
> > At very least requires changes [#356 (comment)](https://github.com/privacyguides/privacyguides.org/pull/356#issuecomment-974866065)
> 
> What are the changes you're referring to?
> 
> > However that being said I do believe we could split that video-streaming page into two sections.
> > ```
> > Services which host content (peertube, lbry)
> > Services which are frontends to youtube (invidious, freetube, newpipe).
> > ```

I've made this change like you asked.
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If we do this we should have a warning:
> > ```
> > Invidious is not private and forwards all video requests to googlevideo.com (unless you add &local=true to the URL
> > Invidious/PeerTube: If your threat model requires privacy you should use a VPN or Tor (some invidious instances do allow for .onion access so that is something that "enhances privacy"
> > ```
> 
> These?

**Comment by dngray** [comment]
Anyway, Closing this PR. We'll look into re-establishing Invidious/Peertube, one could argue these support some privacy enhancing feature (ie .onion support etc).

**Comment by julianfairfax** [comment]
Closing a PR doesn't solve the issue being discussed. As mentioned in #358, you didn't even follow proper procedure when adding LBRY. Acting like this and then closing pull requests makes you look like what Privacy Tools is doing. If you can't work with the community or follow your own procedure, neither of you are doing the community a service.

**Comment by PinkDev1** [comment]
> And do you want this site to be endorsing nazis

We do not endorse the users. We endorse the technology and its resistance against censorship.

Just like any new technology, it can be used for good and for evil, but that doesn't mean that it should be discarded all together.

**Comment by dngray** [comment]
> Acting like this and then closing pull requests makes you look like what Privacy Tools is doing

It's closed because it is superseeded by https://github.com/privacyguides/privacyguides.org/pull/358

As for re-adding invidious/peertube, this will be done under a separate PR. PRs should not do multiple things at once (generally).

**Comment by julianfairfax** [comment]
How can it be superseded by #358 when you've locked #358? You close the one PR and then lock the supposed new one.

**Comment by julianfairfax** [comment]
> > And do you want this site to be endorsing nazis
> 
> We do not endorse the users. We endorse the technology and its resistance against censorship.
> 
> Just like any new technology, it can be used for good and for evil, but that doesn't mean that it should be discarded all together.
> 
> LBRY should stay

The problem is you endorse the service operators, who seem to endorse the users.

**Comment by PinkDev1** [comment]
The PR has been closed yet some of its editions are supported by the community.[1](https://www.reddit.com/r/PrivacyGuides/comments/qy7ozx/recent_updates_to_privacyguidesorg/hlef3s4/).

Indivious should be re-added with the asked warnings. Peertube should be a discussion of its own.

**Comment by julianfairfax** [comment]
It doesn't seem listening to the community is a factor anymore.

**Pull request closed without merging**
