### PR TITLE
Hebrew, French, Dutch - Test

### PR DESCRIPTION
**Pull request by jonaharagon**
- [ ] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [ ] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [ ] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

### CODE REVIEW

**Comment by dngray** [comment]
Does appear to be an issue with the Hebrew version not taking RTL. I thought this would have been automatic for RTL languages https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#directionality

**Comment by dngray** [comment]
I think I know what might be causing the RTL issue:

Spotted this in the deploy log:

5:48:49 PM: WARNING  -  Language he_IL is not supported by mkdocs-material==9.0.11+insiders.4.30.0, not setting the 'theme.language' option

We know Hebrew is supported, so maybe the `he_IL` code is wrong and its defaulting back to LTR.

**Comment by blacklight447** [comment]
The start your privacy journey is broken in the preview, gives a 404.

**Comment by dngray** [comment]
I fixed the directionality issue by changing `he_IL` to `he`:

```
find docs/ -type f -name "*.he_IL.*"  | xargs -r rename -v ".he_IL" ".he"
find theme/overrides/ -type f -name "*.he_IL.*"  | xargs -r rename -v ".he_IL" ".he"
```

And making sure to update it in `mkdocs.yml`.

**Comment by jonaharagon** [comment]
Re-done in #2022.

**Pull request closed without merging**
