### PR TITLE
Ente Auth has now desktop apps available for all platforms

### PR DESCRIPTION
**Pull request by rollsicecream**
Changes proposed in this PR:

- Ente Auth has now desktop apps available for all platforms

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

### CODE REVIEW

**Comment by jonaharagon** [comment]
Am I blind, or where are you seeing that on this page?

**Comment by rollsicecream** [comment]
> Am I blind, or where are you seeing that on this page?

https://ente.io/download

**Comment by jonaharagon** [comment]
So, sounds like I can close this then 😅

**Comment by rollsicecream** [comment]
Well, the app is available, only on GitHub for now.

https://mstdn.social/@ente/112179300441817939

**Comment by jonaharagon** [comment]
Ahh. I looked at their [README](https://github.com/ente-io/ente/tree/main/auth) too and it lied to me. I see.

Okay if we link to the GitHub releases that's good 👍

**Comment by rollsicecream** [comment]
Is this link good? https://github.com/ente-io/ente/releases?q=auth

Since it's a monorepo, I find necessary to the search results for the keyword "auth".

**Comment by jonaharagon** [comment]
Oh cool, yeah I noticed that, and was thinking about what the best way to handle that would be. Sounds perfect 👍

**Review by dngray — APPROVED** [review]

**Review by freddy-m — APPROVED** [review]

**Pull request merged**
