### PR TITLE
Add links to JSON & RSS feeds on blog page

### PR DESCRIPTION
**Pull request by lx-is**
Resolves: #769  & #796 

I built a popup that allows for picking between the JSON feed and the RSS feed. It doesn't use JavaScript, for those who care.

### Changes

<details>
  <summary>Add a RSS logo in the blog title</summary>

</details>

<details>
  <summary>Add a feed selection popup</summary>

</details>

<details>
  <summary>Add a link to the feed selector in the footer</summary>

</details>

### CODE REVIEW

**Comment by gracjankn** [comment]
I think the icon and popup look nice, but the title should remain at the top and the paragraph is unnecessary. I made a pull request with this changes and aria-label for people using assistive technologies like screen readers (by default Font Awesome icons are not accessible).

**Comment by lx-is** [comment]
This is still a work in progress

**Comment by gracjankn** [comment]
That's alright. I wouldn't have came up with this popup on my own and I think it was really well executed.

**Comment by lx-is** [comment]
> I think it was really well executed.

Thanks 😊

> aria-label for people using assistive technologies like screen readers

I think this is a site-wide issue. Maybe you could look into implementing aria-label for all the missing areas?

**Comment by gracjankn** [comment]
> I think this is a site-wide issue. Maybe you could look into implementing aria-label for all the missing areas?


That is a good idea. I'll look into it.

**Pull request closed without merging**
