### PR TITLE
Add Notesnook

### PR DESCRIPTION
**Pull request by thecodrr**
Changes proposed in this PR:

- Add Notesnook to Notebooks as [per the approved discussion](https://discuss.privacyguides.net/t/notesnook-evernote-alternative/174/47)

Conflict of interest:

I am the lead developer of Notesnook. Please review the suggested changes carefully and let me know if there is something that needs to be changed.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Comment by jonaharagon** [comment]
Is this the only version of this logo available? I'm not sure if it looks the best in light mode on our site, but if that's the intent then it's fine.

**Comment by thecodrr** [comment]
@jonaharagon unfortunately, our official logo is black on white which makes it merge with the white background. An alternative could be to add a drop shadow to make it distinguishable. Other than that there's not much that can be done.

**Review by mfwmyfacewhen — APPROVED** [review]

**Comment by thecodrr** [comment]
@jonaharagon what's the status on this? Can we get this included if there's no issue?

**Comment by dngray** [comment]
Just curious why this was placed at #1. Typically we put things as they are added, or if an option like Standard Notes has had an audit, it gets the primary slot.

**Comment by thecodrr** [comment]
@dngray I have no issue with moving NN up or down. There's no ulterior motive behind the top placement but if it affects how users might perceive certain things, I have no issue with moving it further down. However, I see no specific guide on how placement really works on PG so that might be something that should be included at the end of each section so future additions might not make the same mistake.

**Pull request merged**
