### PR TITLE
Add some other threat modeling links

### PR DESCRIPTION
**Pull request by dngray**
This incorporates discussions from

- https://github.com/privacyguides/privacyguides.org/discussions/740

Note I did not include https://teamsammut.com/scf/ as it seems not really to our target audience. We could use a [graphic on that page](https://teamsammut.com/files/images/scf-boxes.jpg) like that though. On a side note, I do like some of the pictures used in this article https://opsec101.org

- https://github.com/privacyguides/privacyguides.org/discussions/1631

### CODE REVIEW

**Review by mfwmyfacewhen — APPROVED** [review]

**Comment by jonaharagon** [comment]
#740 saying that this page needs improvements is very out of date, we discussed this page extremely thoroughly when we did #1819 and #1276 and I think we were all happy with it, I don't really know what this adds.

If you like information from these other websites, I would rather that information be incorporated onto this page and those links added to the sources section instead, generally speaking I don't think we should direct people elsewhere for further reading.

**Comment by dngray** [comment]
> If you like information from these other websites, I would rather that information be incorporated onto this page and those links added to the sources section instead, generally speaking I don't think we should direct people elsewhere for further reading.

Yes, which is why I did mark this as a draft. It is more of a reminder for me to think about how it could fit into the page.

**Comment by freddy-m** [comment]
Do we still want to do this @privacyguides/team?

**Comment by jonaharagon** [comment]
I don't think we still want to do this, no.

**Comment by dngray** [comment]
Agreed, we don't really need to do this anymore, we've got a better page IMO

**Pull request closed without merging**
