### PR TITLE
Enable new mkdocs-material features

### PR DESCRIPTION
**Pull request by jonaharagon**
Changes proposed in this PR:

- Enables [instant link previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews)
- moves more translations to env variables

LeYAi6UHW54Gzwmt

I'm not sure what I think about these. Give them a spin and let me know what you think.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

### CODE REVIEW

**Comment by dngray** [comment]
Taking a look at this, I'm not sure I like the preview thing. Seems like it causes a lot of clutter say when mousing over buttons on the tools page.

**Comment by redoomed1** [comment]
After a cursory test of the instant link previews, I will note that there's one case where the preview is not that useful: when hovering over the [General Criteria](https://www.privacyguides.org/en/about/criteria/) link.
criteria-pop-up
I think that the previews for "whole page links" cover anything until the first permalink on the page, which explains the above behavior.

**Comment by jonaharagon** [comment]
We can easily make a change to make this more meaningful with this feature in mind:

jarmMGa97Z6jGZxU

**Comment by jonaharagon** [comment]
In the long term, instant link previews will be a critical component in replacing all the wikipedia links, links like those, and abbreviations in `abbreviations.en.txt` which _aren't actually abbreviations_ across the website as well. For example (not in this PR, but in the future I'm looking to add an internal "privacy glossary" to provide this functionality): 

image

**Comment by dngray** [comment]
> replacing all the wikipedia links, links like those, and abbreviations in `abbreviations.en.txt` which _aren't actually abbreviations_ across the website as well. For example (not in this PR, but in the future I'm looking to add an internal "privacy glossary" to provide this functionality):

Sounds like a good idea, I checked a few pages of this now and everything seems to be working great.

**Pull request merged**
