### PR TITLE
Show forum topics on homepage

### PR DESCRIPTION
**Pull request by jonaharagon**
Our homepage is of course our most trafficked page, but despite this it hasn't really changed at all in years. This would make it a bit more dynamic for new visitors.

Adds two different sections to the page:

7VKBqZB15kKMKpiV

QSe3QuClYOWB6QeX

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Comment by redoomed1** [comment]
The new sections display weirdly on Mullvad Browser (Safer _and_ Standard security level).

topics-week_mb-safer

new-topics_mb-safer

Otherwise, they look great on other browsers! (Tested in Firefox+Arkenfox and Vanadium, appears as displayed in the initial post in this PR)

**Comment by jonaharagon** [comment]
Funny, I honestly don't know why it _did_ work in other browsers actually. Good catch, should be fixed.

**Comment by redoomed1** [comment]
> should be fixed.

Can confirm it's fixed!
topics-fixed_mullvad-browser

**Review by freddy-m — COMMENTED** [review]
I don't mind the idea of having some recent forum topics on the homepage, but I'm not too keen on how this looks in particular. It's very text heavy... I'd also be a tad worried if someone spammed the forum and accordingly was able to get onto the main site.

Perhaps a sidebar of some sort would be better. I like the idea but I'm not sure if this is the best way of doing it.

**Pull request merged**
