### PR TITLE
Update Jitsi Meet instances link

### PR DESCRIPTION
**Pull request by elitejake**
## Description

Jitsi Meet's wiki has been migrated to [jitsi.github.io/handbook](https://jitsi.github.io/handbook/).<sup>[ref]</sup>

[ref]: https://github.com/jitsi/jitsi-meet/wiki

### CODE REVIEW

**Comment by ph00lt0** [comment]
resolved in: https://github.com/privacyguides/privacyguides.org/pull/192

**Comment by tommytran732** [comment]
Ah yeah we are not recommending Jitsi Meet anymore since it's end to end encryption support for group call is in alpha and it hasn't been audited yet, so I am closing this.

**Comment by ph00lt0** [comment]
@tommytran732 although i agree that it would be important to do so, do we have any other recommendations for conference calling? A feature I really like is that I can give people the Jitsi meet phone number and meeting pin so that they call over phone as they request/demand without having to set up yet another temporary phone number.

**Comment by ph00lt0** [comment]
> @tommytran732 although i agree that it would be important to do so, do we have any other recommendations for conference calling? A feature I really like is that I can give people the Jitsi meet phone number and meeting pin so that they call over phone as they request/demand without having to set up yet another temporary phone number.

Maybe this would be more suited in a VOIP and conferencing call section, which was suggested earlier. Most of us need to do these type of normal and groups calls, so it is still worth to recommend the best options for these imo.

**Comment by tommytran732** [comment]
> > @tommytran732 although i agree that it would be important to do so, do we have any other recommendations for conference calling? A feature I really like is that I can give people the Jitsi meet phone number and meeting pin so that they call over phone as they request/demand without having to set up yet another temporary phone number.
> 
> Maybe this would be more suited in a VOIP and conferencing call section, which was suggested earlier. Most of us need to do these type of normal and groups calls, so it is still worth to recommend the best options for these imo.

I think it is better to just not recommend anything at all than recommending questionable products. When Jitsi Meet is ready, we will add it back.

**Comment by ph00lt0** [comment]
@tommytran732 i think that is pretty strong worded for an open source project that actually tries to do right. I get where you  are coming from but if the privacy community wouldn't recommend alternatives everyone would still be using Zoom. Same goes for VOIP, it isn't perfect, but better then calling with your own number. When no prefect solution is available it can still be beneficial to look into how to layer defenses and limit the amount of data you'd have to provide.
I don't think we should compare Jitsi to something like element, they serve a different purpose. I would urge to recommend the best options for everyday internet users, not only tools who provide the highest standard. 
For the same reason, we should be telling people it is better to use a different OS if your on windows, but still provide windows users with guidance on how to stop telemetry etc.

**Comment by ph00lt0** [comment]
Moved this discussion here: https://github.com/privacyguides/privacyguides.org/discussions/498

**Pull request closed without merging**
