### PR TITLE
Remove LineageOS

### PR DESCRIPTION
**Pull request by freddy-m**
## Description

Removed LineageOS - Calyx and Graphene are better alternatives.

### CODE REVIEW

**Comment by dngray** [comment]
This is good to do in preparation for https://github.com/privacyguides/privacyguides.org/issues/290 as we'll be requiring verified boot and encryption at rest from any new roms/devices

**Review by dngray — APPROVED** [review]

**Comment by zecamigo** [comment]
Aren't you guys confusing privacy with security?

**Comment by julianfairfax** [comment]
Exactly, this leaves all non-Pixel users thinking they have no options, which is most users.

**Comment by pm4rcin** [comment]
I think it could be added as worth mentioning maybe with a warning or asterisk about "verified boot". In my opinion this should satisfy everyone. And also mention to use "Official" LineageOS Builds or trust the maintainer with "Unofficial".

**Comment by freddy-m** [comment]
> Aren't you guys confusing privacy with security?

Not really. While we are a site focused on privacy, we wouldn't want to recommend something that was insecure when there are alternatives available. Hence, we recommend Calyx and Graphene which are both private and (especially in the case of Graphene) secure.

**Comment by zecamigo** [comment]
> While we are a site focused on privacy, we wouldn't want to recommend something that was insecure when there are alternatives available.

I understand and agree both are interdependent. However, what is the threat model you are working with here? You would have a real high security profile to have to defend against an evil maid attack on your device. 

If you want to profile guidance for high risk investigative journalists, maybe you'll have to remove about half of the services you recommend, because for example you know now that many mail providers will give out user's IP's to the government.

Or maybe I'm missing something about the risks of not having a verified boot?

**Comment by zecamigo** [comment]
Another example, you still recommend Signal even though it is known that they're hosted on PRISM-connected companies and that the secure enclaves have vulnerabilities for that exact scenario, server was closed sourced for over a year, and other red flags. However no word on XMPP. So you're hosted on MicroSoft server, recommended devices made by Google and other services with known issues, however your reluctant to recommend a community powered alternative because of a high security (basically affects you if you're targetted) issue.

**Comment by pm4rcin** [comment]
> Another example, you still recommend Signal even though it is known that they're hosted on PRISM-connected companies and that the secure enclaves have vulnerabilities for that exact scenario, server was closed sourced for over a year, and other red flags.

Yes it's true that Signal is hosted there but it doesn't matter since the main idea of Signal is that the server could be compromised and even then your messages are still secure. You can even use Signal with Tor easily like Snowden does. There were some more red flags with Signal like the crypto but there are FLOSS forks which removes binary blobs and could remove the crypto thing if it'll come to an app.

Regarding the rest I think I agree. If your device gets stolen you should probably reinstall stock ROM or contact a service or something to securely extract the data you want and reset phone to factory defaults. But take this with a big grain of salt since I'm not an expert on phones security.

**Comment by TheFrenchGhosty** [comment]
@freddy-m @dngray 

>Removed LineageOS - Calyx and Graphene are better alternatives.

Calyx and Graphene are available, on at most, 5 devices, LineageOS is available dozens of devices. Calyx and Graphene are better than LineageOS, sure, but they are in no way an alternative to it. LineageOS, when degoogled, is perfectly fine privacy wise.

**Comment by tommytran732** [comment]
> @freddy-m @dngray
> 
> > Removed LineageOS - Calyx and Graphene are better alternatives.
> 
> Calyx and Graphene are available, on at most, 5 devices, LineageOS is available dozens of devices. Calyx and Graphene are better than LineageOS, sure, but they are in no way an alternative to it. LineageOS, when degoogled, is perfectly fine privacy wise.

DivestOS exists. Did you even read the site?

**Comment by dngray** [comment]
We recommend optimal solutions. You should always buy hardware to meet software needs and not the other way around. It's worth noting not all lineageos builds are maintained to the same level of quality, and they don't really provide any "privacy" enhancing features when compared to some other random rom that doesn't include gapps.

The site is moving towards creating criteria for most/all sections. We're looking at quality over quantity approach which slowly tightens as products improve.

**Comment by TheFrenchGhosty** [comment]
>You should always buy hardware to meet software needs and not the other way around.

That's now how the world works.

**Comment by dngray** [comment]
> That's now how the world works.

Says who? Please stop spamming closed PRs thanks. I don't care what your agenda is.

> Then stop recommending 3/4 awful stuff.

We're slowly refining the pages as we create criteria/research for each one.

**Pull request merged**
