### PR TITLE
Remove icon from external source

### PR DESCRIPTION
**Pull request by elitejake**
The icon is not necessary and it is loaded from an external source. So, I removed it.

### CODE REVIEW

**Comment by jonaharagon** [comment]
Yikes, kind of annoyed that any of these are external actually, since the other icons are not. *Investigating*

**Comment by jonaharagon** [comment]
I would rather wait and see if https://github.com/squidfunk/mkdocs-material/issues/3851 can be resolved, since we use more emojis than just this one.

**Comment by elitejake** [comment]
You're right. It totally slipped my mind that this was a bug in the Privacy plugin.

**Comment by jonaharagon** [comment]
Closing this. Best case the Privacy plugin is updated. Worst case scenario I'd rather put together a PR that manually adds all the emojis we use the same way as our other custom icons, instead of this. Which would be annoying, but I'd rather not go without emojis :)

**Pull request closed without merging**
