### PR TITLE
Filen cloud storage

### PR DESCRIPTION
**Pull request by DanielProg39**
It is a PR for Filen cloud storage. I am an enthusiast, no one is paying me for this and there is no affiliate links in commit (even though I have one). I just think that it is a great cloud storage as it puts privacy and security first. No other traditional cloud storage put this much attention to it, except ProtonDrive, Sync and MEGA. However, each of them have significant drawbacks compared to Filen. For example, Sync is proprietary and MEGA has a little tangled [Terms](https://mega.io/terms) and [Privacy policy](https://mega.io/privacy) and has some [privacy](https://tosdr.org/en/service/306) and [security](https://blog.mega.io/mega-security-update/) issues.

Filen site: https://filen.io/

### CODE REVIEW

**Comment by tommytran732** [comment]
I haven't looked into filen yet but if you are listing it, consider putting Filen above TAHOE-LAFS
Also, I feel like the paragraph should be broken up a bit

**Comment by tommytran732** [comment]
Er yeah, so...
I found 1 issue with their service (unrelated to their encryption), reported, and they replied within a few minutes, which is pretty good. They have escalated it, we'll see how long it takes for them to actually fix it.

If we do recommend them, I think they should be listed as #2, as having a client doing encryption like they do is a lot better than using a web client like ProtonDrive.

**Comment by dngray** [comment]
Few things fixed in https://github.com/privacyguides/privacyguides.org/pull/345/commits/3cd885176929556c6ba4a95ef53dfd389fdd8b1f

also :+1:  on the feedback @tommytran732 gave.

**Comment by freddy-m** [comment]
Just a small note: generally, we prefer people to open [discussions](https://github.com/privacyguides/privacyguides.org/discussions) before submiting PRs 👍🏼

**Comment by DanielProg39** [comment]
> Just a small note: generally, we prefer people to open [discussions](https://github.com/privacyguides/privacyguides.org/discussions) before submiting PRs 👍🏼

Sorry, I didn't know about it. Thank you!

**Comment by samuel-lucas6** [comment]
This actually has a [discussion](https://github.com/privacyguides/privacyguides.org/discussions/67). I don't recommend listing it considering the vulnerabilities I found, some of which were severe. They've improved since then, but I still wouldn't trust it to necessarily be vulnerability free. That discussion also points out that Filen is [not](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md#modified-read-only-license) [free and open source](https://opensource.org/licenses/alphabetical).

**Comment by tommytran732** [comment]
> This actually has a [discussion](https://github.com/privacyguides/privacyguides.org/discussions/67). I don't recommend listing it considering the vulnerabilities I found, some of which were severe. They've improved since then, but I still wouldn't trust it to necessarily be vulnerability free. That discussion also points out that Filen is [not](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md#modified-read-only-license) [free and open source](https://opensource.org/licenses/alphabetical).

My my... I wonder what those vulnerabilities were related to?

**Comment by samuel-lucas6** [comment]
> > This actually has a [discussion](https://github.com/privacyguides/privacyguides.org/discussions/67). I don't recommend listing it considering the vulnerabilities I found, some of which were severe. They've improved since then, but I still wouldn't trust it to necessarily be vulnerability free. That discussion also points out that Filen is [not](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md#modified-read-only-license) [free and open source](https://opensource.org/licenses/alphabetical).
> 
> My my... I wonder what those vulnerabilities were related to?

I've been tempted to write up a blog post considering how many people seem to be promoting Filen. I've been extremely busy though, and I hoped they'd disclose the issues publicly. They never did as far as I'm aware. 

In summary, they weren't authenticating ciphertexts when using AES-CBC (an unauthenticated mode), they used an insecure password-based KDF, the way they derived IVs was very weird and may have led to reuse, they weren't doing client-side password hashing properly, and they used an insecure random number generator. Things like lack of authentication and an insecure random number generator are cryptography 101 type things a developer should know about from doing basic reading (e.g. just library documentation, not even touching blog posts, online courses, or books).

**Comment by tommytran732** [comment]
> > > This actually has a [discussion](https://github.com/privacyguides/privacyguides.org/discussions/67). I don't recommend listing it considering the vulnerabilities I found, some of which were severe. They've improved since then, but I still wouldn't trust it to necessarily be vulnerability free. That discussion also points out that Filen is [not](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md#modified-read-only-license) [free and open source](https://opensource.org/licenses/alphabetical).
> > 
> > 
> > My my... I wonder what those vulnerabilities were related to?
> 
> I've been tempted to write up a blog post considering how many people seem to be promoting Filen. I've been extremely busy though, and I hoped they'd disclose the issues publicly. They never did as far as I'm aware.
> 
> In summary, they weren't authenticating ciphertexts when using AES-CBC (an unauthenticated mode), they used an insecure password-based KDF, the way they derived IVs was very weird and may have led to reuse, they weren't doing client-side password hashing properly, and they used an insecure random number generator. Things like lack of authentication and an insecure random number generator are cryptography 101 type things a developer should know about from doing basic reading (e.g. just library documentation, not even touching blog posts, online courses, or books).

Holy wackamoly... have they fixed most of that yet?

**Comment by samuel-lucas6** [comment]
> > > > This actually has a [discussion](https://github.com/privacyguides/privacyguides.org/discussions/67). I don't recommend listing it considering the vulnerabilities I found, some of which were severe. They've improved since then, but I still wouldn't trust it to necessarily be vulnerability free. That discussion also points out that Filen is [not](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md#modified-read-only-license) [free and open source](https://opensource.org/licenses/alphabetical).
> > > 
> > > 
> > > My my... I wonder what those vulnerabilities were related to?
> > 
> > 
> > I've been tempted to write up a blog post considering how many people seem to be promoting Filen. I've been extremely busy though, and I hoped they'd disclose the issues publicly. They never did as far as I'm aware.
> > In summary, they weren't authenticating ciphertexts when using AES-CBC (an unauthenticated mode), they used an insecure password-based KDF, the way they derived IVs was very weird and may have led to reuse, they weren't doing client-side password hashing properly, and they used an insecure random number generator. Things like lack of authentication and an insecure random number generator are cryptography 101 type things a developer should know about from doing basic reading (e.g. just library documentation, not even touching blog posts, online courses, or books).
> 
> Holy wackamoly... have they fixed most of that yet?

They should have fixed all of those yes, but that doesn't mean there aren't more things, like I was concerned about the ciphertext chunks potentially being able to be rearranged since they're using random nonces rather than a counter nonce. You're not even really meant to use a random nonce with AES-GCM, but it's ok if each key is unique or you don't encrypt much data. I haven't looked into that though. The app.js file is 7,763 lines long. They told me they were planning on getting an audit, but I don't know how they'd afford that.

I should also mention that they ignored some of my questions when I was reporting the vulnerabilities, they didn't follow my primary algorithm recommendations, they didn't have a whitepaper until I complained, they used a personal GitHub account until I suggested they set up an organisation, they took weeks to fix spelling/grammar mistakes on the website, and they use RSA encryption rather than hybrid encryption, which is no longer recommended.

**Comment by tommytran732** [comment]
@samuel-lucas6 damn... well that is indeed bad,,,

Oh, since you seem to know cryptography, what do you think of ProtonDrive and Mega? I heard Mega getting mentioned a lot but I haven't looked into it (usually I look at infra stuff and what not because I don't know cryptography lol)

**Comment by samuel-lucas6** [comment]
> @samuel-lucas6 damn... well that is indeed bad,,,

It could be perfectly secure now, but I personally won't be using it. Even audits [miss things](https://soatok.blog/2021/11/05/threema-three-strikes-youre-out/#issues-with-threema-android) and even experienced individuals make [mistakes](https://www.daemonology.net/blog/2011-01-18-tarsnap-critical-security-bug.html). Using a regular cloud storage provider alongside a file encryption tool is the best solution, but I know it's less convenient.

> Oh, since you seem to know cryptography, what do you think of ProtonDrive and Mega? I heard Mega getting mentioned a lot but I haven't looked into it (usually I look at infra stuff and what not because that's what I am familiar with and I don't know cryptography lol)

I'm very much still learning, and I'm afraid I haven't looked. I think someone told me MEGA does some weird stuff, but I might be making that up. I expect ProtonDrive is all right, but a lot of these services rely on more traditional algorithms like AES, PBKDF2, and RSA, whereas there's been an increasing shift to things like ChaCha20, scrypt/Argon2, and X25519 (e.g. [WireGuard](https://www.wireguard.com/protocol/), [TLS 1.3](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.3), [Noise Protocol Framework](https://noiseprotocol.org/noise.html#dh-functions-cipher-functions-and-hash-functions)). I would argue that the shift is sensible, especially in the case of PBKDF2 and RSA. AES is still good, but it has some limitations, and everybody defaults to AES-GCM, which is not the best. There are some newer AES based algorithms that will likely get more usage soon though.

**Comment by DanielProg39** [comment]
> > @samuel-lucas6 damn... well that is indeed bad,,,
> 
> It could be perfectly secure now, but I personally won't be using it. However, even audits [miss things](https://soatok.blog/2021/11/05/threema-three-strikes-youre-out/#issues-with-threema-android), and even experienced individuals make [mistakes](https://www.daemonology.net/blog/2011-01-18-tarsnap-critical-security-bug.html), so you can never be sure besides lots of peer review. I would argue using a regular cloud storage provider alongside a file encryption tool is the best solution, but I know it's less convenient.
> 
> > Oh, since you seem to know cryptography, what do you think of ProtonDrive and Mega? I heard Mega getting mentioned a lot but I haven't looked into it (usually I look at infra stuff and what not because that's what I am familiar with and I don't know cryptography lol)
> 
> I'm very much still learning, and I'm afraid I haven't looked. I think someone told me MEGA does some weird stuff, but I might be making that up. I expect ProtonDrive is all right, but a lot of these services rely on more traditional algorithms like AES, PBKDF2, and RSA, whereas there's been an increasing shift to things like ChaCha20, scrypt/Argon2, and X25519 (e.g. [WireGuard](https://www.wireguard.com/protocol/), [TLS 1.3](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.3), [Noise Protocol Framework](https://noiseprotocol.org/noise.html#dh-functions-cipher-functions-and-hash-functions)). I would argue that the shift is sensible, especially in the case of PBKDF2 and RSA. AES is still good, but it has some limitations, and everybody defaults to AES-GCM, which is not the best. There are some newer AES based algorithms that will likely get more usage soon though.

Regarding MEGA. The problem is the need for the user to fully trust the Mega server. Encryption takes place on the client side using javascript, the code of which is downloaded anew from the server each time and can be replaced or disabled at any time, for example as a result of hacking by a third party.

**Comment by samuel-lucas6** [comment]
> Regarding MEGA. The problem is the need for the user to fully trust the Mega server. Encryption takes place on the client side using javascript, the code of which is downloaded anew from the server each time and can be replaced or disabled at any time, for example as a result of hacking by a third party.

Yes, which is why doing file encryption yourself is a safer solution. The good file encryption tools use better algorithms as well.

@tommytran732 Ah here it is. MEGA [uses](https://mega.nz/SecurityWhitepaper.pdf) AES-ECB to encrypt various things, like private keys. AES-ECB should almost never be used because the same plaintext block always becomes the same ciphertext block, which means it doesn't hide patterns in data. There's no reason for them to be using AES-ECB.

From a quick look, they also use a bunch of different modes of operation with AES (AES-ECB, AES-CBC, AES-CTR, AES-GCM, and AES-CCM) rather than just using one, which makes no sense. They're using 128-bit keys for encryption when 256-bit keys would be preferable, especially for long-term storage. They're doing weird hash truncations to 128-bits and 160-bits. They're doing randomly generated 64-bit nonces that get incremented for each chunk when they should just start at 0. They do weird obfuscation for the file key. They use RSA encryption for sharing but X25519 for the chat encryption. The file attributes are encrypted using AES-CBC, but I'm not sure whether there's any authentication. In sum, some odd choices and not the latest algorithms, but I think they've managed to miss some attacks.

ECB

**Comment by DanielProg39** [comment]
> > Regarding MEGA. The problem is the need for the user to fully trust the Mega server. Encryption takes place on the client side using javascript, the code of which is downloaded anew from the server each time and can be replaced or disabled at any time, for example as a result of hacking by a third party.
> 
> Yes, which is why doing file encryption yourself is a safer solution. The good file encryption tools use better algorithms as well.
> 
> @tommytran732 Ah here it is. MEGA [uses](https://mega.nz/SecurityWhitepaper.pdf) AES-ECB to encrypt various things, like private keys. AES-ECB should almost never be used because the same plaintext block always becomes the same ciphertext block, which means it doesn't hide patterns in data. There's no reason for them to be using AES-ECB.
> 
> From a quick look, they also use a bunch of different modes of operation with AES (AES-ECB, AES-CBC, AES-CTR, AES-GCM, and AES-CCM) rather than just using one, which makes no sense. They're using 128-bit keys for encryption when 256-bit keys would be preferable, especially for long-term storage. They're doing weird hash truncations to 128-bits and 160-bits. They're doing randomly generated 64-bit nonces that get incremented for each chunk when they should just start at 0. They do weird obfuscation for the file key. They use RSA encryption for sharing but X25519 for the chat encryption. The file attributes are encrypted using AES-CBC, but I'm not sure whether there's any authentication. In sum, some odd choices and not the latest algorithms, but I think they've managed to miss some attacks.
> 
> ECB

Yeah, I noticed it when was reviewing MEGA. The fact that MEGA uses 128-bit encryption is a bit strange so I decided not to use it even if it implements perfect encyption algoritm (though I noticed that it doesn't).  So I fully agree with you

**Comment by DanielProg39** [comment]
@samuel-lucas6, thank you for everything you told about Filen. I'm not a crazy fan or something, so I admit that I can be wrong in some aspects. I haven't done a code review, so I didn't know anything about Filen's vulnerabilities. Thanks for letting me know.
However, I will still recommend Filen and want it to be added to privacyguides because it's a good service with the best encryption method in the market (idk about ProtonDrive, need to wait till it exit beta). Problems may occur because the service is only one year old and I hope that in near future there will be nothing to complain about

**Comment by tommytran732** [comment]
They did fix their infra (the issue I reported) but they didn't reply to me that they fixed it.

**Comment by saruuto** [comment]
(using alt account)
Someone reported on their discord  that there's a potential risk of leaking directory structure (not file content) as they are sending the hash of file and directory name to the server for de-duplication. I am not sure if it's a major concern or not. Hopefully, they will fix it soon.

https://filen.io/assets/js/fm.min.js

**Comment by samuel-lucas6** [comment]
> @samuel-lucas6, thank you for everything you told about Filen. I'm not a crazy fan or something, so I admit that I can be wrong in some aspects. I haven't done a code review, so I didn't know anything about Filen's vulnerabilities. Thanks for letting me know. However, I will still recommend Filen and want it to be added to privacyguides because it's a good service with the best encryption method in the market (idk about ProtonDrive, need to wait till it exit beta). Problems may occur because the service is only one year old and I hope that in near future there will be nothing to complain about

No problem. However, I would like to reiterate that I disagree with it being listed. It probably still contains vulnerabilities, the bug bounty program is basically not advertised at all (I told them to), they don't advertise the source code well (I told them to), the design was undocumented (I told them to) and is still not documented as well as it could be, the license is not a proper open source license, the team don't reply to some support requests/comments, the company website and whitepaper contained errors that were left unfixed for a while after being reported, and pairing an encryption tool with any other cloud storage provider will lead to better security.

I really don't think you can claim it has the best encryption method on the market when it was previously possible for them to modify your encrypted files undetected. Unfortunately, it looks like [ProtonDrive](https://protonmail.com/blog/protondrive-security/) uses PGP, which has a bad reputation.

> They did fix their infra (the issue I reported) but they didn't reply to me that they fixed it.

What does 'infra' mean? Infrastructure? That's the sort of thing they did to me.

> Someone reported on their discord that there's a potential risk of leaking directory structure (not file content) as they are sending the hash of file and directory name to the server for de-duplication. I am not sure if it's a major concern or not. Hopefully, they will fix it soon.

That's interesting.

**Comment by tommytran732** [comment]
Yeah, I meant their infrastructure. 
 As for ProtonDrive, do you think it should be listed? When I made the PR for it, I only looked at their infra, and it seems solid. I never looked at the actual code for encryption itself.
 
 On another note, Nextcloud encryption is only for the files inside of a directory. The directory name itself is still visible to the server, however.

**Comment by samuel-lucas6** [comment]
> Yeah, I meant their infrastructure.
> As for ProtonDrive, do you think it should be listed? When I made the PR for it, I only looked at their infra, and it seems solid. I never looked at the actual code for encryption itself.
> 
> On another note, Nextcloud encryption is only for the files inside of a directory. The directory name itself is still visible to the server, however.

I do given how few decent options there are. At least ProtonDrive is likely to be implemented correctly given the background of the team.

Nextcloud is pretty bad. I've found it to be buggy ever since I started using it, and I know others have too.

**Comment by youdontneedtoknow22** [comment]
a question to the cryptographic gurus here. Does Mega encrypt files with their client on the client-side? All of their Apps are open source and on github.
If yeah, it's safe to assume that they are safe, just like filen right? (without mentioning their privacy policy, I'm just talking about the files you upload to their servers).

**Comment by ph00lt0** [comment]
> Nextcloud is pretty bad. I've found it to be buggy ever since I started using it, and I know others have too.

Yep nextcloud especially it's E2EE implementation is very buggy. Wouldn't recommend to use it unless self hosted (own hardware). I am a huge fan of there effort and try to help out but it's not near where it should be. https://github.com/nextcloud/end_to_end_encryption/issues/248 opened this issue sometime ago, but this behavior has been present for a while. You can work around it eventually but that's not viable for the average user.

**Comment by samuel-lucas6** [comment]
> Does Mega encrypt files with their client on the client-side?

@youdontneedtoknow22 Yes, section 1.2 of their [whitepaper](https://mega.nz/SecurityWhitepaper.pdf) says that the encryption is done client-side.

> All of their Apps are open source and on github.

MEGA [doesn't](https://github.com/meganz/MEGAsync/blob/master/LICENCE.md#mega-limited-code-review-licence) use an [official](https://opensource.org/licenses/alphabetical) open source license, so they're not truly open source.

> If yeah, it's safe to assume that they are safe, just like filen right? (without mentioning their privacy policy, I'm just talking about the files you upload to their servers).

Yes and no. Neither is guaranteed to be secure. As I've explained above, both have some dodgy cryptography going on. However, I'd trust MEGA to be more secure because they're a larger company, the developers are bound to be more experienced, they have a proper bug bounty program, and the whitepaper is more detailed. There are better options though.

**Comment by DanielProg39** [comment]
> a question to the cryptographic gurus here. Does Mega encrypt files with their client on the client-side? All of their Apps are open source and on github. If yeah, it's safe to assume that they are safe, just like filen right? (without mentioning their privacy policy, I'm just talking about the files you upload to their servers).

Yes, encryption takes place on the client side using javascript. However, as I mentioned earlier, this javascript code is downloaded anew from the server each time you use the client and can be replaced or disabled at any time, so you need to fully trust the Mega server to properly encrypt/decrypt your files. In worst case scenario this issue can lead to serious consequences, such as files being crashed or access denial due to the client being unable to decrypt files. I don't know for sure if it would be actually possibe for the server to get your encryption key by sending malicious js code as I don't know the Mega apps' structure well, but you must keep in mind that it might be possible.

**Comment by samuel-lucas6** [comment]
> Yes, encryption takes place on the client side using javascript. However, as I mentioned earlier, this javascript code is downloaded anew from the server each time you use the client and can be replaced or disabled at any time, so you need to fully trust the Mega server to properly encrypt/decrypt your files. 

Not all of their applications are written in JavaScript. The web client is JavaScript.

**Comment by joepie91** [comment]
There is also a discussion [over on LowEndTalk](https://lowendtalk.com/discussion/174204/anyone-using-tried-filen-io) where some people (including me) have posted comments about the dubious reliability and security of it. I would not consider Filen trustworthy, and the amount of issues that have cropped up suggests that they haven't *proactively* tried to get it right at all, which means they are untrustworthy even if they fixed every single reported issue.

**Comment by dngray** [comment]
We're looking at [adding a criteria](https://github.com/privacyguides/privacyguides.org/discussions/24#discussioncomment-1744298) at this point filen would not meet that as it hasn't been externally audited.

I think given the l[ess than transparent past](https://github.com/privacyguides/privacyguides.org/pull/345#issuecomment-976415846) regarding vulnerabilities I don't think it would be appropriate at this time.

**Comment by DanielProg39** [comment]
> We're looking at [adding a criteria](https://github.com/privacyguides/privacyguides.org/discussions/24#discussioncomment-1744298) at this point filen would not meet that as it hasn't been externally audited.
> 
> I think given the [less than transparent past](https://github.com/privacyguides/privacyguides.org/pull/345#issuecomment-976415846) regarding vulnerabilities I don't think it would be appropriate at this time.

Wise decision. You're right 👍🏻

**Comment by DanielProg39** [comment]
> There is also a discussion [over on LowEndTalk](https://lowendtalk.com/discussion/174204/anyone-using-tried-filen-io) where some people (including me) have posted comments about the dubious reliability and security of it. I would not consider Filen trustworthy, and the amount of issues that have cropped up suggests that they haven't _proactively_ tried to get it right at all, which means they are untrustworthy even if they fixed every single reported issue.

Thank you, I'll take it into consideration

**Comment by Loki-L1130** [comment]
I think you can look on to this again.

See here : 
image

In their Discord Channel : 
Image

**Comment by Loki-L1130** [comment]
@dngray Maybe you need to reopen this for further discussion.

**Comment by DanielProg39** [comment]
> I think you can look on to this again.
> 
> See here : image
> 
> In their Discord Channel : Image

Thank you. Looking forward to check it as soon as they publish it 👀

**Review by DanielProg39 — COMMENTED** [review]
Thanks for assistance 👍

**Comment by samuel-lucas6** [comment]
'Nothing severe found' suggests some things were found, but more importantly, the fact they didn't disclose the previous issues properly is concerning. If you look at the GitHub releases, they don't even provide a changelog.

**Comment by DanielProg39** [comment]
> 'Nothing severe found' suggests some things were found, but more importantly, the fact they didn't disclose the previous issues properly is concerning. If you look at the GitHub releases, they don't even provide a changelog.

Well, I am very interested in your opinion regarding this report. If you'll read it, please let me know about your opinion 😉

**Comment by joepie91** [comment]
Leaving aside that I've never heard of this auditor, an audit being done doesn't exactly alleviate my concerns. An audit is always an imperfect snapshot in time; if Filen doesn't have at least one developer on staff that is specialized in security and cryptography, it's very likely that new issues will be introduced in the future (which will then of course not be covered by the audit).

There's also more broadly the problem with audits that they are *not* some sort of 'seal of approval' that something is 'secure', even if companies like to use them that way. Audits can only ever tell you what's *insecure*, not what's *secure*, because the auditor themselves is also an imperfect human being and will miss things.

Bottom line: if this audit report is used to provide feedback to the Filen developers on where they are going wrong, then that is a good thing in the long run, because they can learn from it. But I do not believe that an audit report is, in and of itself, a reason to re-evaluate their addition to PG.

**Comment by DanielProg39** [comment]
@joepie91, great words. I'll take it into consideration and try to find out more on the auditor

**Comment by DanielProg39** [comment]
Hi, I need to note that Filen mobile app is now _really_ FOSS: https://github.com/FilenCloudDienste/filen-mobile/blob/master/LICENSE.md

**Comment by julianfairfax** [comment]
I understand the issues raised here, but with the exception of ProtonDrive, none of the other options currently on the cloud storage page are both free and e2ee. Ofc you can self-host them, but that's not exactly free either. If you don't self-host Nextcloud, every free provider I looked at doesn't support e2ee. Filen does. Obviously we shouldn't just assume everything on the internet should be free, but since that is the assumption, and "free" services are we're trying to offer an alternative to, I think at least one option should be listed. In my personal case, I use Filen. I know it has issues, since it doesn't support everything I'd like it to, but it'll get better, and it's a good free alternative to what are surely not privacy-respecting "free" services.

**Comment by Dyrimon** [comment]
> Hi, I need to note that Filen mobile app is now _really_ FOSS: https://github.com/FilenCloudDienste/filen-mobile/blob/master/LICENSE.md

@DanielProg39 Yes, bu their [desktop client](https://github.com/FilenCloudDienste/filen-desktop/blob/master/LICENSE.md) still remains *non-foss*

**Comment by EdwardLangdon** [comment]
@Dyrimon According to this Reddit Post by Filen : https://reddit.com/ta9cq3. They Changed the MROL license GPLv3. 

I am pretty sure, They will soon change the MROL license of Desktop to GPLv3 as soon as they release the Desktop Apps.

**Comment by Dyrimon** [comment]
> @Dyrimon According to this Reddit Post by Filen : https://reddit.com/ta9cq3. They Changed the MROL license GPLv3.
> 
> I am pretty sure, They will soon change the MROL license of Desktop to GPLv3 as soon as they release the Desktop Apps.

Yes, it seems Filen has changed their desktop clinet license to AGPL-3.0 too. Now it is truly FOSS.

**Comment by TechPro424** [comment]
From this issue, what I can infer is that the 2 main problems were as follows:
1) They were not FOSS - which seems to be resolved
2) Encryption was bad - also seems to be resolved, as they state on their homepage that they utilize AES-256 bit encryption (however, people who know cryptography well should probably do more research on this, as I am not well-versed with that subject)

If the second statement were to be true, is there any other reason that I have missed not to recommend Flien?

**Comment by samuel-lucas6** [comment]
> They were not FOSS - which seems to be resolved

That does seem to have been addressed.

> Encryption was bad - also seems to be resolved, as they state on their homepage that they utilize AES-256 bit encryption (however, people who know cryptography well should probably do more research on this, as I am not well-versed with that subject)

The use of AES-256 means absolutely nothing if it's been implemented incorrectly, and AES is not the only algorithm they're using.

The concern is that a cloud storage service is not a beginner project, and they initially wrote code without doing sufficient reading. They then failed to notify users of a vulnerability as far as I know. They still seem to advertise their bug bounty program poorly, and the whitepaper could be more detailed. More recently, they said they had an audit with a company nobody has probably heard of, but I don't think the results were ever released. They're about to have another audit apparently, but we'll see if they actually share the document.

They have improved their protocol, but it could be better, and there are some things that are unclear. It's much safer to encrypt files locally using a program that has lots of eyes on it before uploading them to a well established, reputable provider, like Google, Proton, etc.

**Comment by DanielProg39** [comment]
> If the second statement were to be true, is there any other reason that I have missed not to recommend Flien?

Well, basically, no. But concidering problems they had in the past (mainly issues with encryption), we need valid approval that they had fixed everything. So the main point is that to be concidered trustworthy a new 3rd-party audit should be conducted and its results should be released to the public.
Until then it is completely legitimate that Filen is not listed, as the community needs to make sure that it is safe and trustworthy.

**Comment by AIGeneratedUsername** [comment]
I highly appreciate how people here do analysis and investigation to make sure that a low-quality software will not be listed on "privacyguides".
At the same time, the listed on your website Nextcloud as a suggested software keeps destroying users' files (https://github.com/nextcloud/server/issues/3056) for **almost 6 years.** And this is still not fixed. You you are happy with such critical bugs, then I can submit a PR to update guidelines for software creators.
Based on this, let's be fair for all developers: you either need to lower your demands to "_this software can store user files at least somehow_", or to remove Nextcloud from the listing.

**Comment by DanielProg39** [comment]
@AIGeneratedUsername I would suggest to open a new issue on this topic as your message doesn't quite fit with the subject of this PR. Also, I took a quick look through the mentioned issue and it seems to be fixed in the new versions and not so many people were affected. I would not consider Nextcloud as stable in any terms now, but it's kinda revolutionary software and people love it despite everything, so it may be the case of "this software can do its work at least somehow". I think it's OK in this case

**Comment by dngray** [comment]
> ([nextcloud/server#3056](https://github.com/nextcloud/server/issues/3056)) for **almost 6 years**

That issue *may* looks like contributors [need info](https://github.com/nextcloud/server/issues/3056#issuecomment-1328055138). Relevant PR to Nextcloud https://github.com/privacyguides/privacyguides.org/pull/1901.

> They have improved their protocol, but it could be better, and there are some things that are unclear. It's much safer to encrypt files locally using a program that has lots of eyes on it before uploading them to a well established, reputable provider, like Google, Proton, etc.

For this reason we particularly like Cryptomator.

**Comment by Noir16** [comment]
> > Encryption was bad - also seems to be resolved, as they state on their homepage that they utilize AES-256 bit encryption (however, people who know cryptography well should probably do more research on this, as I am not well-versed with that subject)
> 
> The use of AES-256 means absolutely nothing if it's been implemented incorrectly, and AES is not the only algorithm they're using.
> 
> The concern is that a cloud storage service is not a beginner project, and they initially wrote code without doing sufficient reading. They then failed to notify users of a vulnerability as far as I know. They still seem to advertise their bug bounty program poorly, and the whitepaper could be more detailed. More recently, they said they had an audit with a company nobody has probably heard of, but I don't think the results were ever released. They're about to have another audit apparently, but we'll see if they actually share the document.
> 
> They have improved their protocol, but it could be better, and there are some things that are unclear. It's much safer to encrypt files locally using a program that has lots of eyes on it before uploading them to a well established, reputable provider, like Google, Proton, etc.

Hello, I was looking into that cloud for the purpose of sharing large files.
I would like to know if there are any threatening problems that can occur when uploading E2EE.

Is Proton Drive still the next best thing? (File sharing is my biggest purpose, so neither Picocrypt or Cryptomator are my options.)

**Comment by dngray** [comment]
What I have noticed is the audit doesn't seem to be publicly available. Their [support](https://filen.io/support) page in fact still says:

> Will there be an official security audit?

> Yes, to give our users a further sense of security, Filen will be tested by an external company in the near future. As of today, we can't reveal much about the issue, as no date has been set yet.

**Comment by Noir16** [comment]
> What I have noticed is the audit doesn't seem to be publicly available. Their [support](https://filen.io/support) page in fact still says:
> 
> > Will there be an official security audit?
> 
> > Yes, to give our users a further sense of security, Filen will be tested by an external company in the near future. As of today, we can't reveal much about the issue, as no date has been set yet.

I tested the basic functions and performance, but the upload and file integrity was unstable.
However, downloads are stable and fast.
And I understood through the white paper that E2EE is meaningless now due to AES implementation issues.

so I don't think I will use it yet.

**Comment by Noir16** [comment]
Proton also saw that E2EE had issues (different issues than filen.io) and moved to filen.io.
This is not to say that we trust filen.io, but rather that we chose a more useful service from among those with similar issues.
If a better cloud service comes along, I'll use it, but I haven't found one yet.

**Comment by Noir16** [comment]
They also had an across-the-board system update on February 21.
https://blog.filen.io/statusupdate-21-02-2023/

This hasn't been audited yet, so I wouldn't trust them completely.
However, at some point in the future, we may need to revisit this.

**Comment by CostcoFanboy** [comment]
> This hasn't been audited yet, so I wouldn't trust them completely.

Apologies but can someone explain to me or link me to an explanation of what an audit even proves except for a marketing gimmick?

You can easily just remove the compromising code block, give them access during a certain time range and put it back. I can't see audits being anything else than just a gimmick to sell brownie points to YouTube reviewers.

Unless audits are completely revamped in some way that'd guarantee their usefulness, I don't see the worth into having audits as a barrier of entry.

To me at this point it just seems like gatekeeping trustworthiness away from those that cannot shoulder the immense financial burden of hiring Cure53 hence killing off smaller more humble projects and possibly stifling competition and exponentially intensifying the need for pleasing venture capitalists.

**Comment by dngray** [comment]
> Apologies but can someone explain to me or link me to an explanation of what an audit even proves except for a marketing gimmick?
> 
> You can easily just remove the compromising code block, give them access during a certain time range and put it back. I can't see audits being anything else than just a gimmick to sell brownie points to YouTube reviewers.

Sure you can, but that isn't the purpose of an audit. The purpose of an audit is to discover accidental mistakes, and determine whether the code follows best practices in the industry.

> Unless audits are completely revamped in some way that'd guarantee their usefulness, I don't see the worth into having audits as a barrier of entry.

The point is we don't want to add *insert some web app that claims to do E2EE poorly* to the site. Otherwise we'd be adding [things like Mega](https://mega-awry.io) with all it's serious flaws.

> To me at this point it just seems like gatekeeping trustworthiness away from those that cannot shoulder the immense financial burden of hiring Cure53 hence killing off smaller more humble projects and possibly stifling competition and exponentially intensifying the need for pleasing venture capitalists.

Privacy Guides is not supposed to be considered "free marketing" for any specific project. It is designed to showcase the best of what we think is available.

**Comment by CostcoFanboy** [comment]
> Sure you can, but that isn't the purpose of an audit. The purpose of an audit is to discover accidental mistakes, and determine whether the code follows best practices in the industry.

Cool, so we confirmed those are useless.

> The point is we don't want to add insert some web app that claims to do E2EE poorly to the site. Otherwise we'd be adding things like Mega with all it's serious flaws.

Ok, I understand this being a possibility for code audits, but this completely falls apart for no log audits. A server can incredibly easily remove logging capabilities, rewrite history, etc. then put it back after the audit and get their little audit brownie point. This is still a major financial gatekeeper.

> Privacy Guides is not supposed to be considered "free marketing" for any specific project. It is designed to showcase the best of what we think is available.

That's cool, it's a shame that it's absolutely not true. The entire website was built to be entirely **tool-centric** and not **practice-centric** with fuzzy criteria thrown all over hence it's completely getting used as a **promotional tool**.

**Comment by dngray** [comment]
> falls apart for no log audits

I never said anything about a "no logs audit". The scope of auditing I was referring to was a code quality audit.

There are completely reasonable reasons such as security to have some logging, for example login IPs for an email service. If anonymity is the goal of a user they should never depend on a "no logs" policy, we do not suggest otherwise. We repeatedly suggest throughout the site a VPN or better Tor is a better approach for those services.

> That's cool, it's a shame that it's absolutely not true in practice.

You obviously haven't looked at our website recently. There are many pages which refer to "guides", such as those in the basics section.

**Pull request closed without merging**
