### PR TITLE
Fix indent in email marketing criteria

### PR DESCRIPTION
**Pull request by paulverbeke**
Changes proposed in this PR:

- fixes indent in the marketing criteria section in email.md

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Review by freddy-m — APPROVED** [review]
Good spot 👍

**Review by jonaharagon — APPROVED** [review]

**Comment by jonaharagon** [comment]
@paulverbeke if you wanted to re-sign this commit now that it has the correct name referencing this PR #, so that it's signed with your GPG key, feel free to do so before I merge this... Otherwise I'll just merge this as-is :)

**Comment by paulverbeke** [comment]
> @paulverbeke if you wanted to re-sign this commit now that it has the correct name referencing this PR #, so that it's signed with your GPG key, feel free to do so before I merge this... Otherwise I'll just merge this as-is :)

done ! I forced pushed, or maybe there was a way to sign without force push and loosing co-author ?

**Comment by jonaharagon** [comment]
No, that is exactly what I meant :)

**Pull request merged**
