### PR TITLE
Fix I2P buttons

### PR DESCRIPTION
**Pull request by elitejake**
## Description

Fix I2P buttons.

### CODE REVIEW

**Comment by elitejake** [comment]
What should be the color of the button? Does I2P have a brand color?

**Comment by dngray** [comment]
> What should be the color of the button? Does I2P have a brand color?

No it's supposed to be purple like the one above as it is Tor

**Comment by dngray** [comment]
This one is an error, it shouldn't have an onion logo either.

**Review by dngray — CHANGES_REQUESTED** [review]
We probably need a custom icon for this with like ⠶⠶ or something to represent the logo

**Comment by elitejake** [comment]
They have a bunch of logos here: https://github.com/i2p/i2p.android.base/tree/master/art
@dngray

**Comment by elitejake** [comment]
Here's the updated font file I created. How does it look?
[ptio-font.zip](https://github.com/privacyguides/privacyguides.org/files/7531881/ptio-font.zip)

**Comment by elitejake** [comment]
Doesn't look good but that is their logo.

**Comment by dngray** [comment]
> Here's the updated font file I created. How does it look?

It looks good I think. I like it better than the ⠶⠶ idea I had.

**Pull request merged**
