### PR TITLE
Update NextDNS footnote message in dns.md

### PR DESCRIPTION
**Pull request by archerallstars**
Changes proposed in this PR:

- Update NextDNS footnote message in dns.md regarding the service's logging behavior to reflect the _**opt-out**_ basis that's recently change in 67614c3e174739abbd96c6dccee1b6d3657c6ba4, as it's _only possible_ to specifically requested the logging when the logging is done on an **_opt-in_** basis. 

Since we had already reflected the reality of service regarding the logging on an opt-out basis, this change is necessary.

## The screenshot showing that **clients IPs and domains** will be logged by default on an opt-out basis:
ss

### With an account:
https://github.com/privacyguides/privacyguides.org/assets/1403194/1aedae4a-ec93-4e35-9bd6-a286dbe539c0

### Without an account:
https://github.com/privacyguides/privacyguides.org/assets/1403194/523d2aff-91cb-4a1b-817c-cd799743e353

The discussion about this issue can be found here: https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Review by rollsicecream — APPROVED** [review]
LGTM

**Comment by xe-3** [comment]
This PR adds some needed clarification, but contributes its own inaccuracies  [(see here)](https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/23) It should be explicitly stated that no logs are kept if no account (personal or trial account) is used.

**Comment by archerallstars** [comment]
@xe-3 The footnote specifically stated about **insights and logging features**, which require a user account to be usable, and also their related privacy policy.

Moreover, we can’t guarantee that the no log policy when using the service without the insights and logging features wouldn’t be bogus as well. Maybe a warning banner like it's suggested [**here**](https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/19) would be more appropriated than to include an unrelated policy to the current footnote content.

---

In fact, I would want to suggest a removal of NextDNS from the recommendation altogether. **Is it really a good idea that we caught the service red hand that it's breaking its policy and still recommending it to people?** However, it wouldn't be appropriated to discuss this matter here.

**Comment by xe-3** [comment]
> The footnote specifically stated about insights and logging features, which require a user account to be usable.

The footnote is for [NextDNS as a service.](https://www.privacyguides.org/en/dns/#recommended-providers). Which can be used with or without an account. ControlD is like this also, [and both things are clearly and separately acknowledged in the footnote](https://www.privacyguides.org/en/dns/#fn:3) It would be inconsistent and misleading to treat NextDNS differently.

> we can’t guarantee that the no log policy when using the service without the insights and logging features wouldn’t be bogus as well.

That is true of every 'no log policy' for a remote service out of your control, it applies to NextDNS and to all DNS providers, VPNs, etc, unless they've taken extraordinary steps to make their actual production infrastructure and services transparent.

**Comment by xe-3** [comment]
> Again, it is not related to the current footnote content.

A footnote doesn't refer to itself. It refers to the main body of the text, specifically where the footnote was noted. In this case footnote 5 refers to:
Screenshot from 2024-03-07 15-09-15

The purpose of footnote 5 is to inform users about NextDNS's logging policy.



> Also, using NextDNS without an account should not be recommended, since you can't configure anything

That is a separate topic, but if you believe that, you'd have to submit PR's to remove a number of other DNS providers on the list. Including highly recommended options like Quad9. You'd also have to submit a PR to change the criteria for the DNS category.

**Comment by archerallstars** [comment]
> That is a separate topic, but if you believe that, you'd have to submit PR's to remove a number of other DNS providers on the list. Including highly recommended options like Quad9.

Why? You can configure Quad9 with **[3 different options](https://quad9.net/service/service-addresses-and-features)** without having to create an account. In fact, there's no account and logging request services available on Quad9.

**Comment by dngray** [comment]
Closing in favor of https://github.com/privacyguides/privacyguides.org/pull/2434/files which seems much clearer.

**Pull request closed without merging**
