### PR TITLE
Add Send

### PR DESCRIPTION
**Pull request by d4rklynk**
tracker : #494

### CODE REVIEW

**Comment by d4rklynk** [comment]
> I think it would be a good idea to refer to the project as just 'Send' rather than 'Firefox Send Fork' as branding was intentionally removed for trademark reasons.

Agreed

**Comment by matchboxbananasynergy** [comment]
https://github.com/orgs/privacyguides/discussions/1533#discussioncomment-3166778

**Comment by freddy-m** [comment]
Converting this to a draft, as we are still undecided as to whether we want to recommend this.

**Comment by mfwmyfacewhen** [comment]
This hasn't been approved, wait for the "approved" label on the discussion to make a PR please.

**Pull request closed without merging**
