### PR TITLE
Remove Etag Stoppa

### PR DESCRIPTION
**Pull request by freddy-m**
## Description

Resolves: #55

### CODE REVIEW

**Comment by jonaharagon** [comment]
The mentioned issue says neither are available on Android, can we double-check that? Maybe we should be removing the Android add-ons section entirely.

**Comment by freddy-m** [comment]
> The mentioned issue says neither are available on Android, can we (or did you) double-check that? Maybe we should be removing the Android add-ons section entirely.

Yeah, I've always thought it a bit odd. Can't see any references to Android on their sites, but didin't thoroughly check. Either way, Etag can definitely be removed. And Cookie Auto Delete hasn't been updated since January... 

I'm in favour of removing the secion altogether @privacyguides/team

**Comment by dngray** [comment]
> I'm in favour of removing the secion altogether @privacyguides/team

Agreed. I would like to bring forward https://github.com/privacytools/privacytools.io/pull/2081 and https://github.com/privacytools/privacytools.io/issues/1430 as this section has been neglected.

**Review by jonaharagon — CHANGES_REQUESTED** [review]
Waiting for these changes https://github.com/privacyguides/privacyguides.org/pull/60#issuecomment-918902834

**Comment by youdontneedtoknow22** [comment]
> I'm in favour of removing the secion altogether 

I would love keeping it there and only adding uBO to the list. The web without an adblocker is unusable these days.

**Comment by NSABackdoors** [comment]
Sorry for bumping in but I checked that Etag is not available on Android.

**Comment by dngray** [comment]
> Sorry for bumping in but I checked that Etag is not available on Android.

indeed, that's correct. It is my aim to encorporate https://github.com/privacytools/privacytools.io/pull/2081 into it.

We'll focus more on what settings to enable in the UI, that didn't exist when that page was written.

We'll be moving away from also specifying `about:config` settings, and referring people to arkenfox/user.js on desktop as you can't set those on android/googleplay version anyway.

The plan for that page, is to specify some extensions. Remove ones that aren't relevant/available. On the mobile space, really the only one that *is* relevant is ublock origin.

**Pull request merged**
