### PR TITLE
Update/Fix/Shorten links, optimize svgs and lint

### PR DESCRIPTION
**Pull request by kimg45**
Changes proposed in this PR:

- fixed some outdated links for element
- fixed broken links throughout the site
- shortened/removed country specific parts of App Store links to make them country agnostic and save data
- removed more language/country specific parts of URLs

I checked all the links to make sure they still work but feel free to double check.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Comment by dngray** [comment]
The wikipedia ones will need to be checked. In some cases other languages have very different articles which don't actually have much content. In that case it's probably better using translation services on the en article.

**Comment by kimg45** [comment]
You're right I just looked, re-added en.wikipedia.

**Comment by dngray** [comment]
Just removed all trailing `/` and ran through lint which cleared some whitespace people had added (who don't use linters).

I wonder if we should also remove all instances of `www` maybe.

```
grep -r -P 'www.(?!w3|tempuri)([-\w]*\.)(?!w3|tempuri)\S*'
```

There's a few :grin:

**Comment by dngray** [comment]
I did leave these ones alone, because I don't want to mess with SEO, and it's best to be consistent across whole site @jonaharagon?

- www.privacyguides.org
- www.xoe4vn5uwdztif6goazfbmogh6wh5jc4up35bqdflu6bkdc5cas5vjqd.onion
- www.wikidata.org/wiki/Q111710163
- www.youtube.com/@privacyguides
- www.jonaharagon.com

I also didn't change other links like `xmlns`:

- www.serif.com
- www.w3.org
- www.inkscape.org

Or in license for mathjax

- www.apache.org

Funnily enough these two would not work with `security.ssl.require_safe_negotiation` set to true in Firefox:

- https://www.un.org/en/about-us/universal-declaration-of-human-rights
- https://www.qualcomm.com/news/releases/2020/12/qualcomm-and-google-announce-collaboration-extend-android-os-support-and

Didn't support naked URL

- www.efd.admin.ch/efd/en/home/digitalisierung/swiss-digital-initiative.html

**Comment by kimg45** [comment]
Wow really went above and beyond haha thanks!

**Comment by dngray** [comment]
Someone didn't read https://www.privacyguides.org/en/meta/uploading-images/#svg and I found some of these SVGs weren't optimized.

**Comment by dngray** [comment]
I've squashed this huge PR, because I have checked everything so far and it looks good.

**Pull request merged**
