### PR TITLE
Add some other people

### PR DESCRIPTION
**Pull request by dngray**

### CODE REVIEW

**Review by jonaharagon — DISMISSED** [review]
Websites need to be accurate (or simply removed)

**Comment by dngray** [comment]
> Websites need to be accurate (or simply removed)

oops that was my mistake.

**Comment by freddy-m** [comment]
@privacyguides/team we ought to get on with this, update it with photos, sites and all.

**Comment by dngray** [comment]
> Websites need to be accurate (or simply removed)

This is true. I need to point mine to polarbear.army and finish setting that domain up.

**Pull request closed without merging**
