### PR TITLE
update!: Remove Hypatia, DivestOS, and Mull in light of support ending

### PR DESCRIPTION
**Pull request by friadev**
List of changes proposed in this PR:

- DivestOS has announced they will no longer be supporting their mobile projects including DivestOS, Mull, and Hypatia : https://divestos.org/pages/news#end

### CODE REVIEW

**Comment by friadev** [comment]
> Perhaps the distrubitions page and Android shouldnt now just be merged. I doubt we are going to recommend anything outside grapheneOS in a while

Yeah probably. Also just noticed we call them ROMs

**Comment by friadev** [comment]
> > Perhaps the distrubitions page and Android shouldnt now just be merged. I doubt we are going to recommend anything outside grapheneOS in a while
> 
> Yeah probably. Also just noticed we call them ROMs

I think this should all be a separate PR though the important thing is to remove the EOL software right now.

**Comment by friadev** [comment]
> Lgtm. We take the rewrite of a Android /GOS page outside this PR.

Can you go ahead and approve it in GitHub also

**Review by blacklight447 — APPROVED** [review]
Very unfortunate, but in anycase LGTM.

@SkewedZeppelin thanks for maintaining all these projects over the years, they were of great value and you have helped tons of people of the years. In my eyes, thats something to be proud off.

**Review by freddy-m — APPROVED** [review]

**Pull request merged**
