### PR TITLE
Show backers on donation page

### PR DESCRIPTION
**Pull request by jonaharagon**
Do we have an issue with adding this? https://privacyguides-privacyguides-org-preview-pr-1152.surge.sh/about/donate/#backers

### CODE REVIEW

**Comment by Dyrimon** [comment]
That page is connecting to `cloudflareinsights.com` and `sentry.io` trackers. Is it possible to remove those?

**Comment by freddy-m** [comment]
> Do we have an issue with adding this? 

Not really, though I don't mind the page as it is. Just hope it doesn't encourage the sort of spam we used to get with PTio...

**Comment by dngray** [comment]
> That page is connecting to `cloudflareinsights.com` and `sentry.io` trackers. Is it possible to remove those?

Seems that OpenCollective uses https://www.cloudflare.com/web-analytics, so linking to this does link to that.

Looking through it though, I don't think it is particularly privacy invasive. It only provides some fairly minimal data to OpenCollective, such as location, etc.

If we just linked to the opencollective org https://opencollective.com/privacyguides then it would be the same thing.

**Comment by jonaharagon** [comment]
> Just hope it doesn't encourage the sort of spam we used to get with PTio...

This is less of a sponsorship-type change and more just a statement of fact. Worth pointing out this only links to OpenCollective profiles and not custom links (although of course the profiles could have their own links specified). If we wanted to explore a partner program again I'd probably want to model it after https://www.qubes-os.org/partners/, but we're not making that change now or adding any sponsor-type tier back to Open Collective at the moment.

**Review by dngray — APPROVED** [review]

**Pull request merged**
