### PR TITLE
Make headings consistent and remove redundant descriptions

### PR DESCRIPTION
**Pull request by mfwmyfacewhen**
The title and subtitle are redundant here. Also the blurb about browsing the "dark net" is unnecessary as the title is self-explanatory.

### CODE REVIEW

**Review by lx-is — CHANGES_REQUESTED** [review]
~~Change each network's heading to h2 instead of h3~~

wait nvm, that wouldn't be consistent with other pages

**Review by lx-is — APPROVED** [review]

**Comment by blacklight447** [comment]
Are we sure we don't just wanna replace it rather then just remove? It seems rather emoty without it, and it wouldn't be consistent with the rest of the site which provides small describtions at the top of the page.

**Comment by mfwmyfacewhen** [comment]
> Are we sure we don't just wanna replace it rather then just remove? It seems rather emoty without it, and it wouldn't be consistent with the rest of the site which provides small describtions at the top of the page.

Sure, what do you think should go there? Maybe something like "These networks aren't accessible through a normal browser, you need specific software to use them."

**Review by jonaharagon — CHANGES_REQUESTED** [review]
> wait nvm, that wouldn't be consistent with other pages

probably an indication the other pages should be changed.

**Review by jonaharagon — APPROVED** [review]

**Pull request merged**
