### PR TITLE
Update encrypted DNS information for Apple devices

### PR DESCRIPTION
**Pull request by lx-is**
The inclusion of the 'Secure DNS profile creator' utility could be left out, but I think it serves a useful enough purpose while fitting within *most* threat models. The information that follow its mention allows readers to determine if it's right for them or not. Realistically, unsigned profiles aren't a huge deal — very easily, you can open them in a text editor to verify the [contents](https://user-images.githubusercontent.com/100533118/159229500-5d414e9c-4618-4fd1-8c8c-244ac1401757.png) before installation.

### All changes
- Minor phrasing updates
- Mention the DNS Setting API available to apps
- Mention VPN DNS priority
- Mention Secure DNS profile creator
- Information on signed profiles
- Add link to ControlD signed profiles
- Add macOS instructions (#782)

### CODE REVIEW

**Comment by dngray** [comment]
Going to be taking a look at https://github.com/privacyguides/privacyguides.org/pull/575 next, this probably won't get merged as is, we'll have to rebase once that is complete.

**Comment by lx-is** [comment]
Sounds good. Should I close this for now?

**Comment by DeiAsPie** [comment]
Probably, Yes.

**Comment by dngray** [comment]
I was going to say no, because otherwise we might forget.

**Comment by dngray** [comment]
Not sure how i missed, this draft, but I'll incorporate this in with https://github.com/privacyguides/privacyguides.org/pull/767 and give you co-author.

Will need to be converted to markdown so yeah.

**Comment by dngray** [comment]
@lx-is I've moved this into https://github.com/privacyguides/privacyguides.org/pull/767, if you are happy with it I'll squash and push to main repo.

Do you think it's still worth mentioning DNSCloak?

**Pull request closed without merging**
