### PR TITLE
add DoQ to NextDNS

### PR DESCRIPTION
**Pull request by spaceoden**
NextDNS appears to support DoQ so it should not be omitted.

Edit: previously I suggested including DNSCrypt as well but per discussion below I have removed it.

Changes proposed in this PR:

- Add DoQ to the dns table entry for NextDNS.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Comment by spaceoden** [comment]
Here is where I see DNSCrypt instuctions for NextDNS. I have not tested them.
Screenshot_20230502_110354

**Comment by jonaharagon** [comment]
Interesting, that DNS Stamp is for DNS-over-HTTPS, not the DNSCrypt *protocol*. It might work in DNSCrypt clients that support DoH, but not clients which support the DNSCrypt protocol exclusively.

**Comment by spaceoden** [comment]
Ah, I see. I don't use DNSCrypt or DoQ myself, I just saw them in the NextDNS web interface and assumed they were missing from Privacy Guides due to outdated information or a mistake.

I have now removed DNSCrypt so now this PR only adds DoQ.

**Review by blacklight447 — APPROVED** [review]
After the correction, lgtm.

**Review by dngray — APPROVED** [review]

**Review by jonaharagon — APPROVED** [review]

**Comment by dngray** [comment]
dnscrypt-proxy can do DoH and DoH/3. NextDNS does not support DNSCrypt https://help.nextdns.io/t/p8hsmfq/does-nextdns-really-support-dnscrypt

The stamp would be for configuring dnscrypt-proxy to do DoH

**Pull request merged**
