### PR TITLE
General site-wide consistency updates

### PR DESCRIPTION
**Pull request by lx-is**
PR started off with productivity tool JS warning consistency changes, but dng added some more updates

### CODE REVIEW

**Comment by dngray** [comment]
Wondering whether this should be an a [warning](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) admonishment

**Comment by lx-is** [comment]
> Wondering whether this should be an a [warning](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) admonishment

I'll change it to one to see how it looks with the preview. I think it'll look good

**Comment by lx-is** [comment]
I wonder if the admonitions would look better embedded in the card @dngray

**Comment by dngray** [comment]
We should be more consistent on this. Sometimes the admonisment appears before the card.

There were some I noticed that were inconsistent like the metadata removal (metapho), email clients (apple mail), video streaming (freetube etc), cloud (tahoe-lafs).

We're putting the admonishments outside of the card.

**Comment by dngray** [comment]
I also took the opportunity to fix consistency with the Notebooks page, seems https://github.com/privacyguides/privacyguides.org/pull/820 got misplaced during the migration.

**Comment by dngray** [comment]
I also took the opportunity to update the browsers page in accordance to https://github.com/privacyguides/privacyguides.org/issues/908#issuecomment-1092812825

**Review by dngray — APPROVED** [review]

**Pull request merged**
