### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by Positron832**
## Description
Fixed a typo.
Resolves: eye pain?

### CODE REVIEW

**Comment by dngray** [comment]
>  Resolves: eye pain? 

:laughing: 

You're the first one to notice this.

**Review by unbeatable-101 — APPROVED** [review]
Most important PR I've ever seen.

**Comment by dngray** [comment]
> Most important PR I've ever seen.

Yes it's all @tommytran732's fault in https://github.com/privacyguides/privacyguides.org/commit/a86cffb0bd411e79636acb64676aa5215c5e3477#diff-4873ce540cfbfdf696e1ee18c2289b00b30f5659c90e35144ebe8ea5aa55f145R80

**Comment by tommytran732** [comment]
> > Most important PR I've ever seen.
> 
> Yes it's all @tommytran732's fault in [a86cffb#diff-4873ce540cfbfdf696e1ee18c2289b00b30f5659c90e35144ebe8ea5aa55f145R80](https://github.com/privacyguides/privacyguides.org/commit/a86cffb0bd411e79636acb64676aa5215c5e3477#diff-4873ce540cfbfdf696e1ee18c2289b00b30f5659c90e35144ebe8ea5aa55f145R80)

Stop exposing me in public smh.

**Comment by dngray** [comment]
> Stop exposing me in public smh.

[you rn](https://www.youtube.com/watch?v=1GiPcP30cFc)

**Comment by tommytran732** [comment]
> > Stop exposing me in public smh.
> 
> [you rn](https://www.youtube.com/watch?v=1GiPcP30cFc)

1. Staph
2. Merge the PR
3. Fix da anchor links
4. Werk on da browser PR

**Pull request merged**
