### PR TITLE
Update DuckDuckGo description and logos

### PR DESCRIPTION
**Pull request by lx-is**
polished up the duckduckgo recommendation a bit

### CODE REVIEW

**Comment by dngray** [comment]
I'm thinking we should standardize canvas sizes of our SVGs https://github.com/privacyguides/privacyguides.org/wiki/Contributing#images

**Comment by lx-is** [comment]
> I'm thinking we should standardize canvas sizes of our SVGs https://github.com/privacyguides/privacyguides.org/wiki/Contributing#images

Does that matter when the css sets the size of them anyway?

**Comment by dngray** [comment]
> Does that matter when the css sets the size of them anyway?

Probably not too much, but I like to scour them anyway.

**Review by dngray — APPROVED** [review]

**Comment by lx-is** [comment]
> Probably not too much, but I like to scour them anyway.

I always run them through svgomg, is that bad?

**Comment by elitejake** [comment]
We should create an action to automatically scour SVGs.

**Comment by lx-is** [comment]
Not a bad idea. GitHub Explore uses [ImgBot](https://github.com/apps/ImgBot) and they also use a linter bot.

maybe something for @jonaharagon to look into

**Comment by lx-is** [comment]
> Does [Imgbot](https://github.com/marketplace/imgbot) minify SVGs?

Yes there is a svg in the example picture

**Pull request merged**
