### PR TITLE
Update primary button text

### PR DESCRIPTION
**Pull request by jonaharagon**
Resolves: #1094 

Preview: https://github.com/privacyguides/privacyguides.org/pull/1095#issuecomment-1107909848

### CODE REVIEW

**Review by lx-is — CHANGES_REQUESTED** [review]
I think having "Repository" instead of "Source Code" would be better.

The latter might sound too technical/irrelevant for some people, thus discouraging them from clicking the link. More often than not, repositories house important non-code related information such as wikis and a faq, with the readme sometimes even serving as the project's homepage.

**Comment by jonaharagon** [comment]
@lx-is I actually figured the opposite, "repository" is dev-speak, while more people are probably familiar with the idea of "source code". 

I wonder if we should change the links to the project's README specifically if they are only on a Git repo, and say "View README" or "View Info" instead.

**Comment by lx-is** [comment]
Huh, interesting. I thought repository was a pretty mainstream term nowadays.

I just feel "source code" implies only the raw code, meant for auditing and such. Maybe just me.

I think "___ Info" could work, with the blank being replaced with project, product, software, or whatever.

**Comment by elitejake** [comment]
Or the button text should say `Visit Homepage` instead of `Source Code`. Because it is technically the project's home page.
<hr>

If we _are_ sticking to `Source Code`, I'd say `View Source` would be better,

**Comment by dngray** [comment]
I've gone ahead and changed the others, merge when you want @jonaharagon

**Comment by elitejake** [comment]
@dngray what's the difference between `Visit Website` and `Visit Homepage`?

**Comment by lx-is** [comment]
Should "Visit" even be used at all? Having a verb isn't consistent with the other buttons

**Comment by dngray** [comment]
> @dngray what's the difference between `Visit Website` and `Visit Homepage`?

I used Homepage when the product was a project site, I used Website, when it was a service

**Pull request merged**
