### PR TITLE
Blog replacement

### PR DESCRIPTION
**Pull request by jonaharagon**
Discussion: https://github.com/privacyguides/team/discussions/25

### CODE REVIEW

**Comment by dngray** [comment]
I guess this will break RSS though, which means we'll get requests about that?

**Comment by freddy-m** [comment]
Are we going to hook this up to RSS or will it be done manually? Really like the way it looks just might not be able to constantly update it, thus leading to the problems of stagnation we mentioned earlier.

We could also add a blogroll underneath the recommended articles, linking to blogs we enjoy...

**Comment by jonaharagon** [comment]
It'd be done manually, all you have to do is add the article to [`articles.yml`](https://github.com/privacyguides/privacyguides.org/blob/bfd3f22d318e3f283e07a54c19caaeca7b5b573f/data/articles.yml) so maintaining it is trivial, you can add articles as you tweet them, or I or anyone else can add articles we like easily, doesn't really matter.

I definitely want to manually curate articles, but we could _also_ use something like openring at the bottom of the page like you suggested, I'm just not sure what sources we'd like to add. I think it's probably for the best if we are manually reviewing everything we link to on the website.

**Comment by freddy-m** [comment]
> I think it's probably for the best if we are manually reviewing everything we link to on the website.

You make a good point, potential for some damage if we use an RSS feed. We just need to ensure it recieves at least one new article per week. Perhaps we could say: email suggestions to [idk who's email, probably mine].

**Review by freddy-m — APPROVED** [review]
LGTM

**Review by mfwmyfacewhen — APPROVED** [review]

**Review by blacklight447 — APPROVED** [review]

**Review by dngray — APPROVED** [review]

**Comment by Victor239** [comment]
> You make a good point, potential for some damage if we use an RSS feed. 

I'm not sure what damage there is by using a RSS feed, but it's a real shame that one isn't present currently because that was how I was following this project. I'm not realistically going to check this single website when I get dozens of blogs, YouTube channels, Hacker News feeds and everything else via RSS. Reminds me of proprietary silos like Facebook and Instagram which refuse to allow open-source apps protocols to receive their feeds.

**Comment by jonaharagon** [comment]
@Victor239 that's not what we're referring to there, what we dismissed was pulling articles from RSS feeds we choose to automatically post on https://www.privacyguides.org/articles/. There was some background discussion for this PR that wasn't talked about on this page, but TL;DR we have this "Articles from around the web" page to post links to articles on other sites in addition to our own blog, but what we decided here was that those articles we link to will be manually curated. We should still have an RSS feed hosted by ourselves for this section... I think that was overlooked so it might be broken. I'll open an issue to re-create our RSS feed here now so I don't forget.

For what it's worth, you can follow the changelog of this entire website via RSS here: https://github.com/privacyguides/privacyguides.org/releases.atom

**Comment by Victor239** [comment]
Ah my mistake then, I thought it was removed since my browser extension doesn't detect any RSS feed on https://www.privacyguides.org/articles/ nor https://www.privacyguides.org/blog/2022/06/09/hide-nothing/, but the old URL at https://blog.privacyguides.org/feed/ still works and I'm subscribed to. Glad to hear the normal blog RSS isn't going away then :)

**Comment by jonaharagon** [comment]
Well blog.privacyguides.org is actually going away soon, but I'll make sure we add a feed to www.privacyguides.org before that happens.

**Comment by freddy-m** [comment]
> Well blog.privacyguides.org is actually going away soon, but I'll make sure we add a feed to [www.privacyguides.org](http://www.privacyguides.org/) before that happens.

On that note, where are the old articles published on the site being stored? I'll migrate mine to my blog when it's finally public, but what about Dan's?

**Comment by jonaharagon** [comment]
@freddy-m the ones currently on the site will stay as-is.

**Pull request merged**
