### PR TITLE
Add NewsFlash as a recommendation under 'News Aggregators'

### PR DESCRIPTION
**Pull request by rollsicecream**
[Relevant forum post](https://discuss.privacyguides.net/t/add-newsflash-for-news-aggregators/15814)

Changes proposed in this PR:

- Add NewsFlash as a recommendation under the 'News Aggregators' category of the website.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Comment by rollsicecream** [comment]
I don't know why all Netlify checks have failed.....

**Comment by rollsicecream** [comment]
Any updates?

**Review by jonaharagon — CHANGES_REQUESTED** [review]
leaving reminder that someone needs to add this to `docs/tools.md` before merging

**Comment by rollsicecream** [comment]
Done! It can be merged now.

**Comment by rollsicecream** [comment]
Awaiting review from @jonaharagon.

**Comment by rollsicecream** [comment]
Updates?

**Comment by rollsicecream** [comment]
Any updates on this?

**Review by dngray — APPROVED** [review]

**Review by jonaharagon — APPROVED** [review]

**Comment by dngray** [comment]
This will need a PR shortly after to convert to HTML admonitions https://www.privacyguides.org/en/meta/admonitions/

**Pull request merged**
