### PR TITLE
Remove Croc from recommendations

### PR DESCRIPTION
**Pull request by dngray**
This is a follow up of https://github.com/privacyguides/privacyguides.org/pull/886

We're removing Croc, see issue: https://github.com/schollz/croc/issues/468

We may consider it when https://github.com/schollz/croc/issues/467 is completed.

For now as an alternative, we suggest using Magic Wormhole.

### CODE REVIEW

**Comment by realguyman** [comment]
@dngray As @lx-is already stated, it is still present here (to clarify): https://deploy-preview-927--privacyguides.netlify.app/tools/#file-sharing.

Please remove it there, then we should be ready to merge.

**Comment by samuel-lucas6** [comment]
He has blocked me as I cannot comment on any issues. I don't think there's much hope of SIEC being removed, which is very unfortunate. I'm not sure why RedRocket was unconcerned when [investigating](https://redrocket.club/posts/croc/), although they note weird design decisions in their conclusion. The developer's [blog](https://schollz.com/blog/croc9/) again reinforces the fact that he views SIEC as a good choice.

**Comment by dngray** [comment]
In general, this is something that concerns us, experimental crypto should never make it into products as a default which people depend on.

**Comment by samuel-lucas6** [comment]
> I defaulted croc to P-256 instead of SIEC as of v9.5.3.

A wise decision. If you had clarified your initial reply to the Curve25519 [issue](https://github.com/schollz/croc/issues/467#issuecomment-1088090865), then I would have done the PR for that myself, but you chose **not** to answer my question.

It's notable that you have still **not** removed SIEC despite closing the GitHub [issue](https://github.com/schollz/croc/issues/468), meaning a risk of potential insecurity remains **for a reason you have yet to justify** because you did not respond to my questions.

> Ps. Yeah samuel-lucas6 is banned from croc temporarily for doubling down on troll behavior (inflammatory comments, etc).

My intent was never to troll. However, I was and will continue to be accusatory and infuriated because you are blatantly avoiding my questions, brushing off criticism related to SIEC, and comfortable with your design decisions despite potential harm to your users.

For the final time, let me make myself very clear:
- It is a very large project: croc has [18.9k](https://github.com/schollz/croc/stargazers) stars, [843](https://github.com/schollz/croc/network/members) forks, [148,766](https://tooomm.github.io/github-release-stats/?username=schollz&repository=croc) total downloads, and the previous version (v9.5.2) currently has [15,730](https://tooomm.github.io/github-release-stats/?username=schollz&repository=croc) downloads.
- It is a security related project: the [README](https://github.com/schollz/croc#readme) says '**securely** transfer files and folders' and 'provides **end-to-end encryption**' at the top.
- You have an obligation to the users of the project to attempt to provide security if you are marketing it as secure: there's no warning about SIEC and see above.
- Yet you are using a curve designed by your brother that has received minimal peer review and cryptanalysis despite extremely popular curves being accessible to you and recommended in guidance online and books. You implemented a [PAKE](https://github.com/schollz/pake), meaning you have read into cryptography and are well aware of these facts.

> Like most open-source software, I, the maintainer, have no obligation to any aspect or any use of this software by anyone. 

If you do [not](https://github.com/schollz/croc/issues/468#issuecomment-1090368115) want this security obligation, then I suggest you avoid security projects.

**Comment by schollz** [comment]
> I was and will continue to be accusatory

Then you were and will continue to be a troll and the ban will be permanent.

> you chose not to answer my question

People exhibiting troll-like bheaviors are not worth answering to.

Anyways, this privacy guide is new to me. I think its a great project, but I don't want any part of it. :wave:

**Pull request merged**
