### PR TITLE
Remove CalyxOS, move other items to comparison page

### PR DESCRIPTION
**Pull request by dngray**
It seems to be that CalyxOS isn't able to keep up with security updates currently Chromium 100.0.4896.127 has [75 known security vulnerabilities](https://divestos.org/misc/ch-dates.txt). There doesn't seem to be any pending versions [in review](https://review.calyxos.org/q/chromium), which at the time of writing puts it behind LineageOS.

This is not the first time we've had security concerns about CalyxOS, especially when Android 12 was released and they were [unable to provide security updates for 4 months](https://github.com/privacyguides/privacyguides.org/pull/578), leaving users with vulnerable firmware.

Further I would expect a organization with that kind of turn over ([2019](https://filing-service.s3-us-west-2.amazonaws.com/scanned-pdfs/202004/272800937/18426246/272800937_202004_990_2021041417945954.pdf), [2018](https://filing-service.s3-us-west-2.amazonaws.com/scanned-pdfs/201904/272800937/18525990/272800937_201904_990_2021031617799451.pdf), [2017](https://filing-service.s3-us-west-2.amazonaws.com/scanned-pdfs/201804/272800937/11340672/272800937_201804_990_2019032116184840.pdf), [2016](https://filing-service.s3-us-west-2.amazonaws.com/scanned-pdfs/201704/272800937/15241440/272800937_201704_990_2019032116184841.pdf)), to be able to hire a few full time developers to keep on top of things.

### CODE REVIEW

**Review by mfwmyfacewhen — APPROVED** [review]

**Review by jonaharagon — CHANGES_REQUESTED** [review]
Waiting for dev response

**Comment by jonaharagon** [comment]
I don't see a need to make this change at this time. They are changing their development process going forward to release new versions on time, and the current Chromium version live in their repos is 102.0.5005.78.

I'm also told they plan to [support third-party WebView implementations](https://gitlab.com/CalyxOS/calyxos/-/issues/386) soon, at which point we can recommend Bromite (for example) if we wish.

> Further I would expect a organization with that kind of turn over

They're spending 90+% of their yearly income in these reports already though?

**Comment by tommytran732** [comment]
@jonaharagon 

I am skeptical. This is the third time this has happened. 

First was during the Android 10->11 (admittedly awhile ago, 1 month behind)

The second time is from Android 11->12 (4 months behind on Chromium)

Now its this, 2 months behind.

This is particularly ridiculous because Divest barely got any donation money at all (he's actually losing money, yet he managed to keep them up to date).

Its not our job to remind them everytime their chromium or whatever goes outdated.

If we are not removing them now, I'd suggest that we remove them the next time it happens. Also, I am aware that Divest builds for the OP8T/9 are coming out soon and i am thinking of recommending Divest for those 2 instead.

**Comment by chirayudesai** [comment]
I do agree that being out of date is not good, and we're working on ensuring it doesn't happen again.

> Its not our job to remind them everytime their chromium or whatever goes outdated.

This was merely a coincidence, I was already working on it before this issue was opened. See the timestamps on 10241: Initial import of args.gn | https://review.calyxos.org/c/CalyxOS/platform_external_calyx_chromium/+/10241 and following commits (and even some of the patches, they were WiP locally)

**Comment by dngray** [comment]
Well this is a relief, if it's not intentional, and is moving towards a better process in the future.

For now I agree with closing this. Looking forward to seeing what you do next with the project.

**Pull request closed without merging**
