### PR TITLE
Adds Windows & Linux download for briar desktop

### PR DESCRIPTION
**Pull request by gonzoknows**
- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

### CODE REVIEW

**Comment by gonzoknows** [comment]
Alternatively, this can be changed to https://desktop.briarproject.org/msis/Briar-Desktop.msi for direct download

**Comment by dngray** [comment]
We don't direct link to the installer, but we can now mention Linux too as it seems they're updating their installers now more regularly.

**Comment by gonzoknows** [comment]
> We don't direct link to the installer, but we can now mention Linux too as it seems they're updating their installers now more regularly.

In my commit it's not a direct download it's a page which allows the user to choose, but currently the downloads shows flathub (Linux) this new commit adds the new windows download .msi

**Comment by mfwmyfacewhen** [comment]
I'm not sure why we want the same link multiple times.

**Comment by mfwmyfacewhen** [comment]
> How else would you indicate that the same link contains both a Linux and Windows download?

Just a "Downloads" button.

**Review by mfwmyfacewhen — APPROVED** [review]

**Comment by dngray** [comment]
> I'm not sure why we want the same link multiple times.

It's okay, customarily when the download link is the same for each platform, we just duplicate it.

**Review by dngray — APPROVED** [review]

**Pull request merged**
