### PR TITLE
Append free trial infomation of Ente.io at Photo Management.

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Changes proposed in this PR:

- Append free trial infomation of Ente.io at Photo Management.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

### CODE REVIEW

**Review by freddy-m — APPROVED** [review]
LGTM

**Comment by lamtrinhdev** [comment]
Thank you for correct me, @dngray .

**Comment by redoomed1** [comment]
@lamtrinhdev As a friendly FYI, please read the linked comment below :)

https://github.com/privacyguides/privacyguides.org/pull/2489#issuecomment-2040977320

**Comment by lamtrinhdev** [comment]
Thank you for your support @redoomed1 . I am also used github application editor.

**Review by dngray — APPROVED** [review]

**Pull request merged**
