### PR TITLE
Remove Ubuntu touch

### PR DESCRIPTION
**Pull request by tommytran732**
This PR removes Ubuntu Touch. https://github.com/privacyguides/privacyguides.org/discussions/208

### CODE REVIEW

**Comment by tommytran732** [comment]
I think it's good to go. I removed the Ubuntu touch page, so thats why nothing can link to it.

**Comment by dngray** [comment]
I can't say whether or not this operating system is usable as I don't personally use it myself. It was added to the site a long time ago.

It does appear that there are some budget phones Volla, [Volla X](https://liliputing.com/2021/07/volla-phone-x-rugged-phone-is-available-for-pre-order-with-ubuntu-or-android.html) that support Ubuntu Touch.

However regarding security, I don't believe these even use encryption at rest, unlike modern Android based ROMs, therefore I'm willing to approve this.

**Review by dngray — APPROVED** [review]

**Comment by tommytran732** [comment]
> I can't say whether or not this operating system is usable as I don't personally use it myself. It was added to the site a long time ago.
> 
> It does appear that there are some budget phones Volla, [Volla X](https://liliputing.com/2021/07/volla-phone-x-rugged-phone-is-available-for-pre-order-with-ubuntu-or-android.html) that support Ubuntu Touch.
> 
> However regarding security, I don't believe these even use encryption at rest, unlike modern Android based ROMs, therefore I'm willing to approve this.

There is no encryption at rest for Ubuntu Touch, even on the Volla Phone. I did email them and ask about this.

**Comment by dngray** [comment]
> There is no encryption at rest for Ubuntu Touch, even on the Volla Phone. I did email them and ask about this.

Thanks for that :grin: then yes I'd certainly approve this. It's 2021 almost 2022, all devices should have encryption at rest.

**Comment by TheFrenchGhosty** [comment]
Ubuntu Touch is private... this is literally not even a question, I really don't understand what you are even removing it: no encryption... okay? So what? It's a PHONE. It makes phone calls and send text messages. It's 1000 times more private than any stock android phone, or an Apple device.

Ubuntu Touch is PERFECTLY fine for a **PRIVATE** phone.

**Comment by tommytran732** [comment]
> @tommytran732 @dngray
> 
> Ubuntu Touch is private... this is literally not even a question, I really don't understand what you are even removing it: no encryption... okay? So what? It's a PHONE. It makes phone calls and send text messages. It's 1000 times more private than any stock android phone, or an Apple device.
> 
> Ubuntu Touch is PERFECTLY fine for a **PRIVATE** phone.

Why would you recommend a subpar mobile OS which lacks critical security features (it goes beyond just drive encryption) and is years behind its upstream or it's Android counterpart for a private phone? A phone is not just for random texting - people use it for web browsing, for their encrypted communication, and so on. By your logic everyone should just get a flip phone instead.

**Comment by Guardian-AI-Dusty** [comment]
Imma agree with this statement . 
OP said that Ubuntu Touch is perfectly fine for a Private Phone but that's cause there's not much thing you can do in ubuntu touch .

If we remove all the apps from android and iphone then it will be pretty similar .
And add to the fact that ubuntu touch is not updated that much and considering it lacks some primary security features . It really isn't ideal for use lol .

I mean at this point just get a nokia 3310 then XD

**Comment by TheFrenchGhosty** [comment]
@tommytran732 

>Why would you recommend a subpar mobile OS which lacks critical security features (it goes beyond just drive encryption) and is years behind its upstream or it's Android counterpart for a private phone?

Because it's private.

>A phone is not just for random texting - people use it for web browsing, for their encrypted communication, and so on.

So?

>By your logic everyone should just get a flip phone instead.

Yes, but at least Ubuntu Touch is FOSS.

**Pull request merged**
