### PR TITLE
Update AdGuard & uBlock Origin cards

### PR DESCRIPTION
**Pull request by lx-is**
PR inspired by https://github.com/privacyguides/privacyguides.org/discussions/662#discussioncomment-2375887

Changes:
- Update AdGuard card links
- Recommend to enable AdGuard's *#recommended* filter lists (I would like input on this)
- Add notes about attack surface in regard to filter lists
- Minor grammatical and phrasing updates

### CODE REVIEW

**Comment by mfwmyfacewhen** [comment]
Under Safari sync there is a typo: "Safari only encrypts Safari Bookmarks in transit and stores in an encrypted format." should be "Safari only encrypts Safari Bookmarks in transit and stores **them** in an encrypted format." I have a pr for this but I think I'll just close that and let you fix it in this one.

**Comment by flexagoon** [comment]
How do blocklists increase your attack surface?

**Comment by lx-is** [comment]
> How do blocklists increase your attack surface?

You have to trust for lists not to include malicious rules.

**Comment by mfwmyfacewhen** [comment]
Looks good to me.

**Comment by lx-is** [comment]
> Under Safari sync there is a typo: "Safari only encrypts Safari Bookmarks in transit and stores in an encrypted format." should be "Safari only encrypts Safari Bookmarks in transit and stores **them** in an encrypted format." I have a pr for this but I think I'll just close that and let you fix it in this one.

I think this statement could be expanded upon a bit.

"The synchronization some of data is [not](https://support.apple.com/en-us/HT202303) end-to-end encrypted. While synchronization of Safari History, Tab Groups, and iCloud Tabs are end-to-end encrypted; bookmarks are only encrypted in transit and stored in an encrypted format. As bookmarks are not end-to-end encrypted, Apple may be able to decrypt and access them."

What do you think?

**Comment by dngray** [comment]
> You have to trust lists not to include malicious rules.

Realistically though malicious rules are only going to block things, and prevent them from working. I can't see how this would compromise security of anything.

**Comment by lx-is** [comment]
For filter lists that simply block things, no. But as Sierdy said in https://github.com/privacyguides/privacyguides.org/discussions/662#discussioncomment-2375887 uBO has support for more advanced modification, such as URL-modification.

**Pull request merged**
