### PR TITLE
Fix Nested List

### PR DESCRIPTION
**Pull request by theaeonsolution**
- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

### CODE REVIEW

**Comment by theaeonsolution** [comment]
The nested list Markdown previewed in the GitHub repo is not being displaying properly on https://www.privacyguides.org/vpn/#marketing. The fix can be found in the [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#nested-lists).

**Comment by theaeonsolution** [comment]
Spacing did not fix issue. CSS may need to be reviewed further.

**Comment by jonaharagon** [comment]
What is the issue with the nested list on the site? It appears to be correct to me.

**Comment by theaeonsolution** [comment]
> What is the issue with the nested list on the site? It appears to be correct to me.

The Markdown renders correctly. I was pointing to the styling mismatch from the repo to the website.

The Privacy Guides repo preview reflects this styling:
- List
   - Nested List 

On the Privacy Guides website, the nested list on the VPN Marketing section does not match this styling and I created the PR in case that was not the desired behavior.

**Pull request closed without merging**
