### PR TITLE
Add device integrity/verification recommendations

### PR DESCRIPTION
**Pull request by jonaharagon**
Changes proposed in this PR:

- Recommend [MVT](https://github.com/mvt-project/mvt)
- Recommend iMazing (as an MVT GUI)
- Move Auditor from `android.md` to this new page
- Recommend iVerify (https://discuss.privacyguides.net/t/add-content-about-iverify-for-ios/14579)
- Create new "Advanced" sub-section of tool recommendations

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
While my Hypatia may not be very effective at detecting general malware, it does offer a fairly rigorous database of known stalkerware apps thanks to the @AssoEchap project: https://github.com/AssoEchap/stalkerware-indicators

Maybe of interest.

**Review by dngray — APPROVED** [review]

**Comment by jonaharagon** [comment]
@matchboxbananasynergy what does that mean?

**Review by freddy-m — COMMENTED** [review]
LGTM, however perhaps there should be a warning that this is an advanced section. Even though it is under that category, some people might be alarmed if they hadn't noticed the heading. Thoughts @jonaharagon?

**Review by freddy-m — APPROVED** [review]
LGTM

**Pull request merged**
