### PR TITLE
Add NewPipe x SponsorBlock

### PR DESCRIPTION
**Pull request by tommytran732**

### CODE REVIEW

**Comment by freddy-m** [comment]
Not sure if this should be on the site @privacyguides/team? Seems beyond the scope...

**Comment by tommytran732** [comment]
This fork provides no privacy benefit over Newpipe, but it does'nt make anything worse either, and it seems well-maintained. It does provide a feature that a lotnof people apprefiate, so i thought "Why not?".

It is a lot better than having people install YouTube Vanced if all they want is SponsorBlock.

**Comment by elitejake** [comment]
> but it doesn't make anything worse either,

Doesn't it? I don't think NewPipe with SponsorBlock store offline databases, instead it uses this ([sponsor.ajay.app](https://sponsor.ajay.app/)) public API right?

You should add the [privacy policy](https://gist.github.com/ajayyy/aa9f8ded2b573d4f73a3ffa0ef74f796) of SponsorBlock in the section too.

**Comment by tommytran732** [comment]
> > but it doesn't make anything worse either,
> 
> Doesn't it? I don't think NewPipe with SponsorBlock store offline databases, instead it uses this ([sponsor.ajay.app](https://sponsor.ajay.app/)) public API right?
> 
> You should add the [privacy policy](https://gist.github.com/ajayyy/aa9f8ded2b573d4f73a3ffa0ef74f796) of SponsorBlock in the section too.

SponsorBlock hases the URL, send the first few characters to SponsorBlock, retrieve the list, then search for the exact hash locally. There is not really a privacy issue imo.

Besides, this fork doesn't even have a default sponsorblock instance. If we were to add sponsorblock's TOS, we'd be adding it to FreeTube (which does use sponsor.ajay.app by default), not Newpipe x Sponsorblock.

**Pull request merged**
