### PR TITLE
Remove Microsoft Office suggestion

### PR DESCRIPTION
**Pull request by jonaharagon**
This is plainly ridiculous to me. Even from a security perspective, MDAG is not a standard Office feature, and the default configuration of Office leaves users far more vulnerable to attacks. **Information about using MDAG with Microsoft Office belongs in a Windows guide/tutorial, not a one-line suggestion on this page.** I'm not saying it's not noteworthy, I'm saying this is not the proper place.

This change was originally added in #1423 which describes the PR as "Removes Framadate" and the only discussion of Microsoft Office's MDAG functionality was a single comment in a discussion titled "Remove write.as" - clearly this was not properly discussed in the first place.

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

### CODE REVIEW

**Comment by dngray** [comment]
> **belongs in a Windows guide/tutorial, not a one-line suggestion on this page.** I

That was always the intention, actually in another branch I simply made it a tip.

**Review by dngray — APPROVED** [review]

**Review by mfwmyfacewhen — APPROVED** [review]

**Comment by enviousjag** [comment]
why are you removing the iWork suite?

**Comment by mfwmyfacewhen** [comment]
> why are you removing the iWork suite? Perhaps an oversight? I didn't see iWork being discussed nor is it known to be privacy unfriendly.

It'll be mentioned in the macOS page.

**Comment by dngray** [comment]
Which is why I made a note about it here https://github.com/privacyguides/privacyguides.org/issues/1858#issuecomment-1430883455 so we don't forget.

**Pull request merged**
